window.BAMBOO_LENS_CANDIDATES = {
  "generated_at": "2026-05-06T15:29:19",
  "companies": {
    "nvidia": [
      {
        "title": "NVIDIA Spectrum-X — the Open, AI-Native Ethernet Fabric — Sets the Standard for Gigascale AI, Now With MRC",
        "date": "2026-05-06",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-05-06；标题：NVIDIA Spectrum-X — the Open, AI-Native Ethernet Fabric — Sets the Standard for Gigascale AI, Now With MRC；原文内容：The race to build the world’s most powerful AI factories demands networking that keeps pace with the ambitions of AI itself. NVIDIA Spectrum-X Ethernet scale-out infrastructure stands at the forefront of that race as the most advanced AI networking technology available today, deployed by industry leaders who can’t afford to compromise on performance, resilience or scale. That includes OpenAI , Microsoft and Oracle .；来源：https://blogs.nvidia.com/blog/spectrum-x-ethernet-mrc/",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260506,
        "source_url": "https://blogs.nvidia.com/blog/spectrum-x-ethernet-mrc/",
        "source_excerpt": "The race to build the world’s most powerful AI factories demands networking that keeps pace with the ambitions of AI itself. NVIDIA Spectrum-X Ethernet scale-out infrastructure stands at the forefront of that race as the most advanced AI networking technology available today, deployed by industry leaders who can’t afford to compromise on performance, resilience or scale. That includes OpenAI , Microsoft and Oracle .",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260506-152741__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 7,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "NVIDIA and Corning Announce Long-Term Partnership to Strengthen US Manufacturing for AI Infrastructure",
        "date": "2026-05-06",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-05-06；标题：NVIDIA and Corning Announce Long-Term Partnership to Strengthen US Manufacturing for AI Infrastructure；原文内容：--> PLATFORMS Autonomous Machines Cloud & Data Center Deep Learning & Ai Design & Pro Visualization Healthcare High Performance Computing Self-Driving Cars Gaming & Entertainment other links Developers Industries Shop Drivers Support About NVIDIA View All Products GPU TECHNOLOGY CONFERENCE NVIDIA Blog Community Careers TECHNOLOGIES Newsroom NVIDIA in Brief Exec Bios NVIDIA Blog Podcast Media Assets In the News Press…；来源：https://investor.nvidia.com/news/nvidia-and-corning-announce-long-term-partnership-to-strengthen-us-manufacturing-for-ai-infrastructure",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260506,
        "source_url": "https://investor.nvidia.com/news/nvidia-and-corning-announce-long-term-partnership-to-strengthen-us-manufacturing-for-ai-infrastructure",
        "source_excerpt": "--> PLATFORMS Autonomous Machines Cloud & Data Center Deep Learning & Ai Design & Pro Visualization Healthcare High Performance Computing Self-Driving Cars Gaming & Entertainment other links Developers Industries Shop Drivers Support About NVIDIA View All Products GPU TECHNOLOGY CONFERENCE NVIDIA Blog Community Careers TECHNOLOGIES Newsroom NVIDIA in Brief Exec Bios NVIDIA Blog Podcast Media Assets In the News Press…",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260506-152741__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 5,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "先读交易/客户/合作的规模、期限、收入路径和利润影响；避免只凭标题判断。"
      },
      {
        "title": "NVIDIA and ServiceNow Partner on New Autonomous AI Agents for Enterprises",
        "date": "2026-05-05",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-05-05；标题：NVIDIA and ServiceNow Partner on New Autonomous AI Agents for Enterprises；原文内容：Enterprise AI has learned to generate. It has learned to reason. Now companies are asking the next question: How should AI act? Early agent systems have shown what’s possible, moving beyond simple prompts to take on more complex tasks. The next step is bringing those capabilities into enterprise environments — where agents must operate with context, control and consistency across real workflows. At ServiceNow Knowle…；来源：https://blogs.nvidia.com/blog/servicenow-autonomous-ai-agents-enterprises/",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260505,
        "source_url": "https://blogs.nvidia.com/blog/servicenow-autonomous-ai-agents-enterprises/",
        "source_excerpt": "Enterprise AI has learned to generate. It has learned to reason. Now companies are asking the next question: How should AI act? Early agent systems have shown what’s possible, moving beyond simple prompts to take on more complex tasks. The next step is bringing those capabilities into enterprise environments — where agents must operate with context, control and consistency across real workflows. At ServiceNow Knowle…",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260506-152741__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 3,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "It’s Gonna Be May: 16 Games Hit the Cloud This Month, With More NVIDIA GeForce RTX 5080 Power",
        "date": "2026-04-30",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-04-30；标题：It’s Gonna Be May: 16 Games Hit the Cloud This Month, With More NVIDIA GeForce RTX 5080 Power；原文内容：[Editor’s note] The blog has been updated to note that GeForce RTX 5080-power expansion also extends to the Install-to-Play library. It’s gonna be May — and the cloud’s in full festival mode. 16 games are joining GeForce NOW this month, including new AAA titles arriving on launch day from Steam, Xbox, PC Game Pass and GOG, so members can stream their PC libraries instantly across almost any device. Headline launches…；来源：https://blogs.nvidia.com/blog/geforce-now-thursday-may-2026-games-list/",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260430,
        "source_url": "https://blogs.nvidia.com/blog/geforce-now-thursday-may-2026-games-list/",
        "source_excerpt": "[Editor’s note] The blog has been updated to note that GeForce RTX 5080-power expansion also extends to the Install-to-Play library. It’s gonna be May — and the cloud’s in full festival mode. 16 games are joining GeForce NOW this month, including new AAA titles arriving on launch day from Steam, Xbox, PC Game Pass and GOG, so members can stream their PC libraries instantly across almost any device. Headline launches…",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260506-152741__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "skipped",
        "status_label": "暂不研判",
        "review_lane": "低信号",
        "review_score": 3,
        "review_reason": "这类内容更偏品牌、生态或营销更新，暂时看不到足够直接的业务、财务或估值影响。",
        "read_next": "保留存档；除非后续出现客户、金额、产品路线或财务影响，否则不升级。"
      },
      {
        "title": "Nemotron Labs: What OpenClaw Agents Mean for Every Organization",
        "date": "2026-04-30",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-04-30；标题：Nemotron Labs: What OpenClaw Agents Mean for Every Organization；原文内容：Editor’s note: This post is part of the Nemotron Labs blog series, which explores how the latest open models, datasets and training techniques help businesses build specialized AI systems and applications on NVIDIA platforms. Each post highlights practical ways to use an open stack to deliver real value in production — from transparent research copilots to scalable AI agents. By early 2026, the open source project O…；来源：https://blogs.nvidia.com/blog/what-openclaw-agents-mean-for-every-organization/",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260430,
        "source_url": "https://blogs.nvidia.com/blog/what-openclaw-agents-mean-for-every-organization/",
        "source_excerpt": "Editor’s note: This post is part of the Nemotron Labs blog series, which explores how the latest open models, datasets and training techniques help businesses build specialized AI systems and applications on NVIDIA platforms. Each post highlights practical ways to use an open stack to deliver real value in production — from transparent research copilots to scalable AI agents. By early 2026, the open source project O…",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260506-152741__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 3,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "NVIDIA Sets Conference Call for First-Quarter Financial Results",
        "date": "2026-04-29",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-04-29；标题：NVIDIA Sets Conference Call for First-Quarter Financial Results；原文内容：--> PLATFORMS Autonomous Machines Cloud & Data Center Deep Learning & Ai Design & Pro Visualization Healthcare High Performance Computing Self-Driving Cars Gaming & Entertainment other links Developers Industries Shop Drivers Support About NVIDIA View All Products GPU TECHNOLOGY CONFERENCE NVIDIA Blog Community Careers TECHNOLOGIES Newsroom NVIDIA in Brief Exec Bios NVIDIA Blog Podcast Media Assets In the News Press…；来源：https://investor.nvidia.com/news/nvidia-sets-conference-call-for-first-quarter-financial-results-6919947",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260429,
        "source_url": "https://investor.nvidia.com/news/nvidia-sets-conference-call-for-first-quarter-financial-results-6919947",
        "source_excerpt": "--> PLATFORMS Autonomous Machines Cloud & Data Center Deep Learning & Ai Design & Pro Visualization Healthcare High Performance Computing Self-Driving Cars Gaming & Entertainment other links Developers Industries Shop Drivers Support About NVIDIA View All Products GPU TECHNOLOGY CONFERENCE NVIDIA Blog Community Careers TECHNOLOGIES Newsroom NVIDIA in Brief Exec Bios NVIDIA Blog Podcast Media Assets In the News Press…",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260506-152741__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 11,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "NVIDIA Launches Nemotron 3 Nano Omni Model, Unifying Vision, Audio and Language for up to 9x More Efficient AI Agents",
        "date": "2026-04-28",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-04-28；标题：NVIDIA Launches Nemotron 3 Nano Omni Model, Unifying Vision, Audio and Language for up to 9x More Efficient AI Agents；原文内容：AI agent systems today juggle separate models for vision, speech and language — losing time and context as they pass data from one model to the other. Unveiled today, NVIDIA Nemotron 3 Nano Omni is an open multimodal model that brings these capabilities together into one system, enabling agents to deliver faster, smarter responses with advanced reasoning across video, audio, image and text. This best-in-class model…；来源：https://blogs.nvidia.com/blog/nemotron-3-nano-omni-multimodal-ai-agents/",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260428,
        "source_url": "https://blogs.nvidia.com/blog/nemotron-3-nano-omni-multimodal-ai-agents/",
        "source_excerpt": "AI agent systems today juggle separate models for vision, speech and language — losing time and context as they pass data from one model to the other. Unveiled today, NVIDIA Nemotron 3 Nano Omni is an open multimodal model that brings these capabilities together into one system, enabling agents to deliver faster, smarter responses with advanced reasoning across video, audio, image and text. This best-in-class model…",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260506-152741__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 3,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Into the Omniverse: Manufacturing’s Simulation-First Era Has Arrived",
        "date": "2026-04-28",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-04-28；标题：Into the Omniverse: Manufacturing’s Simulation-First Era Has Arrived；原文内容：Editor’s note: This post is part of Into the Omniverse , a series focused on how developers, 3D practitioners, and enterprises can transform their workflows using the latest advances in OpenUSD and NVIDIA Omniverse . Manufacturing’s traditional design-build-test cycle rested on a single assumption: Real-world testing was the only reliable test environment. Today, high-fidelity simulation produces synthetic training…；来源：https://blogs.nvidia.com/blog/manufacturing-simulation-first/",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260428,
        "source_url": "https://blogs.nvidia.com/blog/manufacturing-simulation-first/",
        "source_excerpt": "Editor’s note: This post is part of Into the Omniverse , a series focused on how developers, 3D practitioners, and enterprises can transform their workflows using the latest advances in OpenUSD and NVIDIA Omniverse . Manufacturing’s traditional design-build-test cycle rested on a single assumption: Real-world testing was the only reliable test environment. Today, high-fidelity simulation produces synthetic training…",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260506-152741__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 3,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      }
    ],
    "tsmc": [
      {
        "title": "TSMC Debuts A13 Technology at 2026 North America Technology Symposium",
        "date": "2026-04-23",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-04-23；标题：TSMC Debuts A13 Technology at 2026 North America Technology Symposium；来源：http://pr.tsmc.com/english/news/3302",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260423,
        "source_url": "http://pr.tsmc.com/english/news/3302",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260506-152741__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "promoted",
        "status_label": "已入库",
        "review_lane": "正式事件",
        "review_score": 14,
        "review_reason": "这条候选已经完成原文研判，并沉淀为正式事件；不再作为待读候选重复出现。",
        "read_next": "可直接进入对应公司主页或事件详情阅读正式研判。"
      },
      {
        "title": "TSMC Files Annual Report on Form 20-F for 2025",
        "date": "2026-04-16",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-04-16；标题：TSMC Files Annual Report on Form 20-F for 2025；来源：http://pr.tsmc.com/english/news/3300",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260416,
        "source_url": "http://pr.tsmc.com/english/news/3300",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260506-152741__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 7,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "适合周末深读：补风险、业务结构、资本开支和治理信息，先不要直接写成短期动作。"
      },
      {
        "title": "TSMC Reports First Quarter EPS of NT$22.08",
        "date": "2026-04-16",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-04-16；标题：TSMC Reports First Quarter EPS of NT$22.08；来源：http://pr.tsmc.com/english/news/3297",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260416,
        "source_url": "http://pr.tsmc.com/english/news/3297",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260506-152741__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 5,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "TSMC March 2026 Revenue Report",
        "date": "2026-04-10",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-04-10；标题：TSMC March 2026 Revenue Report；来源：http://pr.tsmc.com/english/news/3294",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260410,
        "source_url": "http://pr.tsmc.com/english/news/3294",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260506-152741__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 5,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "TSMC February 2026 Revenue Report",
        "date": "2026-03-10",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-03-10；标题：TSMC February 2026 Revenue Report；来源：http://pr.tsmc.com/english/news/3290",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260310,
        "source_url": "http://pr.tsmc.com/english/news/3290",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260506-152741__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 5,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "TSMC Board of Directors Meeting Resolutions",
        "date": "2026-02-10",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-02-10；标题：TSMC Board of Directors Meeting Resolutions；来源：http://pr.tsmc.com/english/news/3287",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260210,
        "source_url": "http://pr.tsmc.com/english/news/3287",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260506-152741__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "TSMC January 2026 Revenue Report",
        "date": "2026-02-10",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-02-10；标题：TSMC January 2026 Revenue Report；来源：http://pr.tsmc.com/english/news/3284",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260210,
        "source_url": "http://pr.tsmc.com/english/news/3284",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260506-152741__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 5,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "TSMC Reports Fourth Quarter EPS of NT$19.50",
        "date": "2026-01-15",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-01-15；标题：TSMC Reports Fourth Quarter EPS of NT$19.50；来源：http://pr.tsmc.com/english/news/3281",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260115,
        "source_url": "http://pr.tsmc.com/english/news/3281",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260506-152741__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 5,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      }
    ],
    "inovance": [
      {
        "title": "2026春季爆品发布会",
        "date": "2026-03-16",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-03-16；标题：2026春季爆品发布会；来源：https://www.inovance.com/portal-front/api/product/launch/listPage?pageNum=1&pageSize=10",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260316,
        "source_url": "https://www.inovance.com/portal-front/api/product/launch/listPage?pageNum=1&pageSize=10",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260506-152741__www.inovance.com_portal-front_api_product_launch_listPage_pageNum_1_pageSize_10.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "2025年度爆品发布会",
        "date": "2025-09-01",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-09-01；标题：2025年度爆品发布会；来源：https://www.inovance.com/portal-front/api/product/launch/listPage?pageNum=1&pageSize=10",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250901,
        "source_url": "https://www.inovance.com/portal-front/api/product/launch/listPage?pageNum=1&pageSize=10",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260506-152741__www.inovance.com_portal-front_api_product_launch_listPage_pageNum_1_pageSize_10.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "邀请函｜ 「零碳有“数” ·智造有“方”」——2025汇川技术纺织行业新品发布会",
        "date": "2025-06-17",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-06-17；标题：邀请函｜ 「零碳有“数” ·智造有“方”」——2025汇川技术纺织行业新品发布会；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%96%B0%E5%93%81&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250617,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%96%B0%E5%93%81&showChannel=2",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260506-152741__www.inovance.com_portal-front_api_home_search_key_%E6%96%B0%E5%93%81_showChannel_2.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "数自融合，绿创未来！汇川技术应需而动，为纺织行业再推新品！",
        "date": "2022-11-21",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2022-11-21；标题：数自融合，绿创未来！汇川技术应需而动，为纺织行业再推新品！；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%96%B0%E5%93%81&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20221121,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%96%B0%E5%93%81&showChannel=2",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260506-152741__www.inovance.com_portal-front_api_home_search_key_%E6%96%B0%E5%93%81_showChannel_2.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "关于汇川技术机器人产品价格调整的通知",
        "date": "2026-03-30",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-03-30；标题：关于汇川技术机器人产品价格调整的通知；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260330,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260506-152741__www.inovance.com_portal-front_api_home_search_key_%E6%9C%BA%E5%99%A8%E4%BA%BA_showChannel_2.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "汇川技术机器人斩获德国TUV功能安全认证，全球化征程再添“安全引擎”",
        "date": "2025-05-09",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-05-09；标题：汇川技术机器人斩获德国TUV功能安全认证，全球化征程再添“安全引擎”；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250509,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260506-152741__www.inovance.com_portal-front_api_home_search_key_%E6%9C%BA%E5%99%A8%E4%BA%BA_showChannel_2.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "120000小时！汇川大六关节机器人MTBF认证达行业顶尖水平",
        "date": "2024-10-10",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2024-10-10；标题：120000小时！汇川大六关节机器人MTBF认证达行业顶尖水平；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20241010,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260506-152741__www.inovance.com_portal-front_api_home_search_key_%E6%9C%BA%E5%99%A8%E4%BA%BA_showChannel_2.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "120000小时！汇川大六关节机器人MTBF认证达行业顶尖水平",
        "date": "2024-10-08",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2024-10-08；标题：120000小时！汇川大六关节机器人MTBF认证达行业顶尖水平；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20241008,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260506-152741__www.inovance.com_portal-front_api_home_search_key_%E6%9C%BA%E5%99%A8%E4%BA%BA_showChannel_2.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      }
    ],
    "gevernova": [
      {
        "title": "4th Quarter 2025 Earnings Webcast",
        "date": "2026-01-28",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-01-28；标题：4th Quarter 2025 Earnings Webcast；来源：https://www.gevernova.com/investors/events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260128,
        "source_url": "https://www.gevernova.com/investors/events",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/gevernova__20260506-152741__www.gevernova.com_investors_events.html",
        "company": "gevernova",
        "company_name": "GE Vernova",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 6,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      }
    ],
    "luxshare": [
      {
        "title": "Luxshare Techday Debuts at Renault TCR: Showcasing Full-Chain Synergy for the Future of Mobility",
        "date": "2026-03-09",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-03-09；标题：Luxshare Techday Debuts at Renault TCR: Showcasing Full-Chain Synergy for the Future of Mobility；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260309,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260506-152741__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "​Gold Forges the Future: Luxshare Precision Once Again Wins Sina Finance's \"ESG Golden Responsibility Award\"",
        "date": "2026-01-19",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-01-19；标题：​Gold Forges the Future: Luxshare Precision Once Again Wins Sina Finance's \"ESG Golden Responsibility Award\"；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260119,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260506-152741__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "World's First! Luxshare Precision USB 40Gbps 240W USB Type-C 3m Active Cable Receives Official Certification",
        "date": "2026-01-05",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-01-05；标题：World's First! Luxshare Precision USB 40Gbps 240W USB Type-C 3m Active Cable Receives Official Certification；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260105,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260506-152741__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Luxshare Precision Named to Forbes' 2025 World's Best Employers List",
        "date": "2025-10-10",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-10-10；标题：Luxshare Precision Named to Forbes' 2025 World's Best Employers List；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20251010,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260506-152741__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Luxshare Precision Soars 65 Places on Fortune Global 500 Ranking!",
        "date": "2025-07-31",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-07-31；标题：Luxshare Precision Soars 65 Places on Fortune Global 500 Ranking!；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250731,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260506-152741__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Luxshare-ICT Tech Day at JLR UK: Shaping the Future of Intelligent Mobility with System-Level Innovations",
        "date": "2025-07-23",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-07-23；标题：Luxshare-ICT Tech Day at JLR UK: Shaping the Future of Intelligent Mobility with System-Level Innovations；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250723,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260506-152741__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "REACH and SVHC Statement",
        "date": "2025-07-22",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-07-22；标题：REACH and SVHC Statement；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250722,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260506-152741__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Luxshare Precision Celebrates Cross-Cultural Unity Through the “Luxshare Cup” Global Relay",
        "date": "2025-07-21",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-07-21；标题：Luxshare Precision Celebrates Cross-Cultural Unity Through the “Luxshare Cup” Global Relay；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250721,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260506-152741__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      }
    ],
    "constellation": [
      {
        "title": "Constellation CEO: &#39;We Produce Enough Energy to Power Mexico&#39;",
        "date": "2026-01-20",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-01-20；标题：Constellation CEO: &#39;We Produce Enough Energy to Power Mexico&#39;；来源：https://www.constellationenergy.com/newsroom.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260120,
        "source_url": "https://www.constellationenergy.com/newsroom.html",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260506-152741__www.constellationenergy.com_newsroom.html.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "ENERGY: Always On",
        "date": "2025-11-18",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-11-18；标题：ENERGY: Always On；来源：https://www.constellationenergy.com/newsroom.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20251118,
        "source_url": "https://www.constellationenergy.com/newsroom.html",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260506-152741__www.constellationenergy.com_newsroom.html.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Aspen Ideas Festival 2025",
        "date": "2025-07-21",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-07-21；标题：Aspen Ideas Festival 2025；来源：https://www.constellationenergy.com/newsroom.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250721,
        "source_url": "https://www.constellationenergy.com/newsroom.html",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260506-152741__www.constellationenergy.com_newsroom.html.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Q1 2026 Constellation Energy Corporation Earnings Conference Call",
        "date": "2026-05-11",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-05-11；标题：Q1 2026 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260511,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260506-152741__investors.constellationenergy.com_events-and-presentations.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 11,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "Constellation Energy Corporation 2026 Business and Earnings Outlook Conference Call",
        "date": "2026-03-31",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2026-03-31；标题：Constellation Energy Corporation 2026 Business and Earnings Outlook Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260331,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260506-152741__investors.constellationenergy.com_events-and-presentations_past-events.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "promoted",
        "status_label": "已入库",
        "review_lane": "正式事件",
        "review_score": 24,
        "review_reason": "这条候选已经完成原文研判，并沉淀为正式事件；不再作为待读候选重复出现。",
        "read_next": "可直接进入对应公司主页或事件详情阅读正式研判。"
      },
      {
        "title": "Q3 2025 Constellation Energy Corporation Earnings Conference Call",
        "date": "2025-11-07",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-11-07；标题：Q3 2025 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20251107,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260506-152741__investors.constellationenergy.com_events-and-presentations_past-events.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 9,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "Q2 2025 Constellation Energy Corporation Earnings Conference Call",
        "date": "2025-08-07",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-08-07；标题：Q2 2025 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250807,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260506-152741__investors.constellationenergy.com_events-and-presentations_past-events.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 9,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "Q1 2025 Constellation Energy Corporation Earnings Conference Call",
        "date": "2025-05-06",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2025-05-06；标题：Q1 2025 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250506,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260506-152741__investors.constellationenergy.com_events-and-presentations_past-events.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 9,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "Q3 2024 Constellation Energy Corporation Earnings Conference Call",
        "date": "2024-11-04",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2024-11-04；标题：Q3 2024 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20241104,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260506-152741__investors.constellationenergy.com_events-and-presentations_past-events.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 9,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "Q2 2024 Constellation Energy Corporation Earnings Conference Call",
        "date": "2024-08-06",
        "fetched_at": "20260506-152741",
        "type": "官方候选",
        "fact": "日期：2024-08-06；标题：Q2 2024 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20240806,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_excerpt": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260506-152741__investors.constellationenergy.com_events-and-presentations_past-events.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 9,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      }
    ]
  }
};
