window.BAMBOO_LENS_CANDIDATES = {
  "generated_at": "2026-05-08T13:10:00",
  "companies": {
    "nvidia": [
      {
        "title": "Linked and Loaded: Gaijin Single Sign-On Now Available on GeForce NOW",
        "date": "2026-05-07",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-05-07；标题：Linked and Loaded: Gaijin Single Sign-On Now Available on GeForce NOW；原文内容：Faster logins mean more time in the gaming action — and this week provides GeForce NOW members with a smoother path straight into the battlefield. Cloud gaming is all about instant access to titles across devices, and the latest GeForce NOW update removes another layer for members jumping into their Gaijin libraries from anywhere. With seven games joining the cloud this week, the action keeps growing — now backed by…；来源：https://blogs.nvidia.com/blog/geforce-now-thursday-gaijin-sso/",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260507,
        "source_url": "https://blogs.nvidia.com/blog/geforce-now-thursday-gaijin-sso/",
        "source_excerpt": "Faster logins mean more time in the gaming action — and this week provides GeForce NOW members with a smoother path straight into the battlefield. Cloud gaming is all about instant access to titles across devices, and the latest GeForce NOW update removes another layer for members jumping into their Gaijin libraries from anywhere. With seven games joining the cloud this week, the action keeps growing — now backed by…",
        "source_body": "Faster logins mean more time in the gaming action — and this week provides GeForce NOW members with a smoother path straight into the battlefield. Cloud gaming is all about instant access to titles across devices, and the latest GeForce NOW update removes another layer for members jumping into their Gaijin libraries from anywhere. With seven games joining the cloud this week, the action keeps growing — now backed by NVIDIA GeForce RTX 5080 performance for Ultimate members across nearly the full GeForce NOW library , spanning both Ready-to-Play and Install-to-Play titles. Gaijin account linking is now cleared for takeoff on GeForce NOW, making it easier to jump straight into battle without extra logins. With Gaijin single sign-on, one quick sign-in connects a Gaijin.net account to the cloud, so supported titles are ready to launch with fewer clicks and no password juggling. Just head to the GeForce NOW app on PC or Mac, dive into the settings and log in under “Connections.” Once linked, supported Gaijin games on GeForce NOW — like the combined-arms chaos of War Thunder — are ready to stream without logging in each time. It’s the same library-first, platform-linking magic members already enjoy with Xbox, Ubisoft Connect and more, now extended to Gaijin so existing PC accounts work seamlessly across devices. Dead as Disco from Brain Jar Game s drops players into a neon-soaked fever dream where every punch, dodge and takedown hits on the beat. This rhythm-infused brawler blends stylish combat with pulsing tracks, turning each fight into a dance floor showdown. Chain combos, stay in sync and keep the groove alive as the chaos escalates. Now available to stream on GeForce NOW, it’s all about timing, flair and fighting like the music never stops In addition, members can look for the following games, all ready to play on GeForce RTX 5080-power for Ultimate members: What are you planning to play this weekend? Let us know on X or in the comments below. What has been your most-played game so far this year? — 🌩️ NVIDIA GeForce NOW (@NVIDIAGFN) May 5, 2026",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260508-130818__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 7,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "NVIDIA and IREN Announce Strategic Partnership to Accelerate Deployment of up to 5 Gigawatts of AI Infrastructure",
        "date": "2026-05-07",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-05-07；标题：NVIDIA and IREN Announce Strategic Partnership to Accelerate Deployment of up to 5 Gigawatts of AI Infrastructure；来源：https://investor.nvidia.com/news/nvidia-and-iren-announce-strategic-partnership-to-accelerate-deployment-of-up-to-5-gigawatts-of-ai-infrastructure",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260507,
        "source_url": "https://investor.nvidia.com/news/nvidia-and-iren-announce-strategic-partnership-to-accelerate-deployment-of-up-to-5-gigawatts-of-ai-infrastructure",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260508-130818__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 5,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "先读交易/客户/合作的规模、期限、收入路径和利润影响；避免只凭标题判断。"
      },
      {
        "title": "Powering the Next American Century: US Energy Secretary Chris Wright and NVIDIA’s Ian Buck on the Genesis Mission",
        "date": "2026-05-07",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-05-07；标题：Powering the Next American Century: US Energy Secretary Chris Wright and NVIDIA’s Ian Buck on the Genesis Mission；原文内容：That’s the case U.S. Energy Secretary Chris Wright and NVIDIA Vice President of Hyperscale and High-Performance Computing Ian Buck made Thursday morning at the SCSP AI+ Expo. The 30-minute fireside chat, moderated by SCSP president Ylli Bajraktari, was called “Powering the Next American Century.” Their argument: American leadership in AI runs through American leadership in energy. “Energy is life,” Wright said. “The…；来源：https://blogs.nvidia.com/blog/energy-secretary-chris-wright-ian-buck/",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260507,
        "source_url": "https://blogs.nvidia.com/blog/energy-secretary-chris-wright-ian-buck/",
        "source_excerpt": "That’s the case U.S. Energy Secretary Chris Wright and NVIDIA Vice President of Hyperscale and High-Performance Computing Ian Buck made Thursday morning at the SCSP AI+ Expo. The 30-minute fireside chat, moderated by SCSP president Ylli Bajraktari, was called “Powering the Next American Century.” Their argument: American leadership in AI runs through American leadership in energy. “Energy is life,” Wright said. “The…",
        "source_body": "That’s the case U.S. Energy Secretary Chris Wright and NVIDIA Vice President of Hyperscale and High-Performance Computing Ian Buck made Thursday morning at the SCSP AI+ Expo. The 30-minute fireside chat, moderated by SCSP president Ylli Bajraktari, was called “Powering the Next American Century.” Their argument: American leadership in AI runs through American leadership in energy. “Energy is life,” Wright said. “The more energy you have, the more affordable energy you have, the more opportunities you have in your society.” The Genesis Mission — the U.S. Department of Energy (DOE)’s effort to apply AI to scientific discovery — is where that case meets execution. NVIDIA is among the DOE partners on the mission, building on what Buck called two decades of NVIDIA building supercomputers with the national labs. “NVIDIA is 100% committed and invested in Genesis,” Buck said. “I’ve never seen more excitement across the lab and industry.” The session was one of several SCSP panels this week with NVIDIA leaders on stage: Cofounder and NVIDIA Fellow Chris Malachowsky will lead a panel on the AI+ Careers Workforce Task Force; Rev Lebaredian will speak on physical AI and simulation; Dion Harris will discuss AI-accelerated American science and AI infrastructure for Africa; and John Josephakis will join a session on U.S. quantum leadership. The DOE brings 17 national labs, the scientists, the national problems and the data. NVIDIA brings the full stack — not just chips, Buck said, but algorithms, methods and 20 years of partnership with the labs. The work is happening at scale. NVIDIA and the DOE are building two AI supercomputers together at Argonne National Laboratory. The first, Equinox, is being stood up now with 10,000 NVIDIA Grace Blackwell GPUs — what Buck called “the same GPU, the same software being used to train and build AI that we’re all enjoying today.” The second, Solstice, will use 100,000 GPUs with NVIDIA Vera Rubin. “To put that 100,000 in perspective on the next-generation GPU, which is dedicated to science, it’s 5,000 exaflops,” Buck said. “That’s a big number that actually is five times larger than the entire TOP500 supercomputer list combined.” “We’re creating all the same technology, all the same hardware, all the same software building blocks used by all the major AI labs around the world,” Buck said, “for all of world science to go get access to.” What that looks like in practice: Buck described an open source NVIDIA AI model trained on 1.5 million physics papers, then fine-tuned on 100,000 papers specifically about fusion. The result is a specialized AI agent DOE researchers can interrogate to advance their work faster. Over the last 20 years, Wright said, the U.S. has tripled oil production and doubled natural gas production — but barely grown electricity production. That’s a problem because, as Wright put it, the most important source of energy for AI is electricity. His department is leaning back into all three pillars of the U.S. grid: natural gas, nuclear and coal.",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260508-130818__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 3,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "NVIDIA Spectrum-X — the Open, AI-Native Ethernet Fabric — Sets the Standard for Gigascale AI, Now With MRC",
        "date": "2026-05-06",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-05-06；标题：NVIDIA Spectrum-X — the Open, AI-Native Ethernet Fabric — Sets the Standard for Gigascale AI, Now With MRC；原文内容：The race to build the world’s most powerful AI factories demands networking that keeps pace with the ambitions of AI itself. NVIDIA Spectrum-X Ethernet scale-out infrastructure stands at the forefront of that race as the most advanced AI networking technology available today, deployed by industry leaders who can’t afford to compromise on performance, resilience or scale. That includes OpenAI , Microsoft and Oracle .；来源：https://blogs.nvidia.com/blog/spectrum-x-ethernet-mrc/",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260506,
        "source_url": "https://blogs.nvidia.com/blog/spectrum-x-ethernet-mrc/",
        "source_excerpt": "The race to build the world’s most powerful AI factories demands networking that keeps pace with the ambitions of AI itself. NVIDIA Spectrum-X Ethernet scale-out infrastructure stands at the forefront of that race as the most advanced AI networking technology available today, deployed by industry leaders who can’t afford to compromise on performance, resilience or scale. That includes OpenAI , Microsoft and Oracle .",
        "source_body": "The race to build the world’s most powerful AI factories demands networking that keeps pace with the ambitions of AI itself. NVIDIA Spectrum-X Ethernet scale-out infrastructure stands at the forefront of that race as the most advanced AI networking technology available today, deployed by industry leaders who can’t afford to compromise on performance, resilience or scale. That includes OpenAI , Microsoft and Oracle . Companies including NVIDIA, Microsoft and OpenAI have demonstrated industry leadership by introducing Multipath Reliable Connection (MRC), an RDMA transport protocol. MRC enables a single RDMA connection to distribute traffic across multiple network paths, improving throughput, load balancing and availability for large-scale AI training fabrics. Think of it as replacing a single-lane road spanning a town with a cleverly laid-out street grid system paired with an on-the-fly traffic app, enabling drivers to reroute around slowdowns and road closures. “Deploying MRC in the Blackwell generation was very successful and was made possible by a strong collaboration with NVIDIA,” said Sachin Katti, head of industrial compute at OpenAI. “MRC’s end-to-end approach enabled us to avoid much of the typical network-related slowdowns and interruptions and maintain the efficiency of frontier training runs at scale.” In addition, Microsoft and NVIDIA have a longstanding collaboration focused on advancing the infrastructure required for the next generation of AI. Microsoft’s Fairwater an d Oracle Cloud Infrastructure (OCI’s) Abilene data center, two of the largest AI factories purpose- built for training and deploying leading-edge frontier LLMs, rely on MRC to deliver on performance, scale and efficiency requirements. NVIDIA Spectrum-X Ethernet is suited for this environment, helping provide the network foundation needed to run large-scale AI models and applications with confidence. Proven first in production with performance optimized on NVIDIA Spectrum-X Ethernet hardware and now released as an open specification through the Open Compute Project, MRC demonstrates the power of the Spectrum-X Ethernet platform: purpose-built hardware, deep telemetry and intelligent fabric control working together to take a new protocol — a set of rules that controls how data moves between two systems across a network — from concept to gigascale AI production. MRC delivers high levels of GPU utilization by load-balancing traffic across all available paths, enabling every GPU to get the bandwidth it needs throughout a training run. It sustains high bandwidth even under congestion by dynamically avoiding overloaded paths in real time. When data loss occurs, intelligent retransmission enables rapid, precise recovery, minimizing the impact of short-lived interruptions to long-running jobs, helping avoid GPU idle time. Administrators also gain fine-grained visibility and control over traffic paths, simplifying operations and accelerating troubleshooting at scale. MRC, deployed on Spectrum-X Ethernet, is optimized and engineered for resilience at massive scale. Its failure bypass technology can — in just microseconds — detect a network path failure and reroute traffic automatically in hardware.",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260508-130818__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 7,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "NVIDIA and Corning Announce Long-Term Partnership to Strengthen US Manufacturing for AI Infrastructure",
        "date": "2026-05-06",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-05-06；标题：NVIDIA and Corning Announce Long-Term Partnership to Strengthen US Manufacturing for AI Infrastructure；来源：https://investor.nvidia.com/news/nvidia-and-corning-announce-long-term-partnership-to-strengthen-us-manufacturing-for-ai-infrastructure",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260506,
        "source_url": "https://investor.nvidia.com/news/nvidia-and-corning-announce-long-term-partnership-to-strengthen-us-manufacturing-for-ai-infrastructure",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260508-130818__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 5,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "先读交易/客户/合作的规模、期限、收入路径和利润影响；避免只凭标题判断。"
      },
      {
        "title": "NVIDIA and ServiceNow Partner on New Autonomous AI Agents for Enterprises",
        "date": "2026-05-05",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-05-05；标题：NVIDIA and ServiceNow Partner on New Autonomous AI Agents for Enterprises；原文内容：Enterprise AI has learned to generate. It has learned to reason. Now companies are asking the next question: How should AI act? Early agent systems have shown what’s possible, moving beyond simple prompts to take on more complex tasks. The next step is bringing those capabilities into enterprise environments — where agents must operate with context, control and consistency across real workflows. At ServiceNow Knowle…；来源：https://blogs.nvidia.com/blog/servicenow-autonomous-ai-agents-enterprises/",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260505,
        "source_url": "https://blogs.nvidia.com/blog/servicenow-autonomous-ai-agents-enterprises/",
        "source_excerpt": "Enterprise AI has learned to generate. It has learned to reason. Now companies are asking the next question: How should AI act? Early agent systems have shown what’s possible, moving beyond simple prompts to take on more complex tasks. The next step is bringing those capabilities into enterprise environments — where agents must operate with context, control and consistency across real workflows. At ServiceNow Knowle…",
        "source_body": "Enterprise AI has learned to generate. It has learned to reason. Now companies are asking the next question: How should AI act? Early agent systems have shown what’s possible, moving beyond simple prompts to take on more complex tasks. The next step is bringing those capabilities into enterprise environments — where agents must operate with context, control and consistency across real workflows. At ServiceNow Knowledge 2026, NVIDIA founder and CEO Jensen Huang joined ServiceNow chairman and CEO Bill McDermott during the opening keynote to discuss the next phase of enterprise AI. The companies are expanding their collaboration across the full stack, delivering specialized autonomous AI agents that are safe and easy to adopt — powered by NVIDIA accelerated computing, open models, domain-specific skills and secure agent execution software, and bringing together enterprise workflow context from ServiceNow Action Fabric and governance from ServiceNow AI Control Tower. ServiceNow is introducing Project Arc , a long-running, self-evolving autonomous desktop agent designed for knowledge workers, including developers, IT teams and administrators. Unlike standalone AI agents, Project Arc connects natively to the ServiceNow AI Platform through ServiceNow Action Fabric to bring governance, auditability and workflow intelligence to every action the autonomous desktop agent takes. It can access the local file systems, terminals and applications installed on a machine to complete complex, multistep tasks that traditional automation can’t handle, but with the controls enterprises actually need to deploy AI at scale. The work is designed based on three requirements every company will need for long-running, autonomous agents: open models and domain-specific skills that can be customized and security that helps agents act without exposing sensitive data or systems — all running on AI factories that deliver efficient tokenomics . Bringing this level of autonomy to enterprises requires control from the start. Project Arc uses NVIDIA OpenShell , an open source secure runtime for developing and deploying autonomous agents in sandboxed, policy-governed environments. ServiceNow is building on and contributing to OpenShell to advance a common foundation for secure, enterprise-grade agent execution. With OpenShell, enterprises can define what an agent can see, which tools it can use and how each action is contained. “Project Arc represents the next step in our ongoing collaboration with NVIDIA, bringing autonomous execution to the desktop,” said Jon Sigler, executive vice president and general manager of AI Platform at ServiceNow. “By combining OpenShell’s runtime layer with ServiceNow AI Control Tower, and powered by ServiceNow Action Fabric, we’re delivering the governance and security that enterprise AI requires.” To be effective, enterprise AI systems must be adaptable. NVIDIA and ServiceNow are building on an open ecosystem that allows organizations to tailor models and applications to their specific domains and data. NVIDIA agent skills enable specialized agents, such as ServiceNow AI Specialists, to deliver targeted capabilities across enterprise workflows. For example, the NVIDIA AI-Q Blueprint for building specialized deep research agents empowers ServiceNow AI Specialists to gather context, synthesize information and support more complex decision-making across business functions.",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260508-130818__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 3,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "It’s Gonna Be May: 16 Games Hit the Cloud This Month, With More NVIDIA GeForce RTX 5080 Power",
        "date": "2026-04-30",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-04-30；标题：It’s Gonna Be May: 16 Games Hit the Cloud This Month, With More NVIDIA GeForce RTX 5080 Power；原文内容：[Editor’s note] The blog has been updated to note that GeForce RTX 5080-power expansion also extends to the Install-to-Play library. It’s gonna be May — and the cloud’s in full festival mode. 16 games are joining GeForce NOW this month, including new AAA titles arriving on launch day from Steam, Xbox, PC Game Pass and GOG, so members can stream their PC libraries instantly across almost any device. Headline launches…；来源：https://blogs.nvidia.com/blog/geforce-now-thursday-may-2026-games-list/",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260430,
        "source_url": "https://blogs.nvidia.com/blog/geforce-now-thursday-may-2026-games-list/",
        "source_excerpt": "[Editor’s note] The blog has been updated to note that GeForce RTX 5080-power expansion also extends to the Install-to-Play library. It’s gonna be May — and the cloud’s in full festival mode. 16 games are joining GeForce NOW this month, including new AAA titles arriving on launch day from Steam, Xbox, PC Game Pass and GOG, so members can stream their PC libraries instantly across almost any device. Headline launches…",
        "source_body": "[Editor’s note] The blog has been updated to note that GeForce RTX 5080-power expansion also extends to the Install-to-Play library. It’s gonna be May — and the cloud’s in full festival mode. 16 games are joining GeForce NOW this month, including new AAA titles arriving on launch day from Steam, Xbox, PC Game Pass and GOG, so members can stream their PC libraries instantly across almost any device. Headline launches include the highly anticipated Forza Horizon 6 and 007 First Light, both ready to hit the cloud on day one. Meanwhile, the GeForce NOW Ultimate membership dials things up with expanded RTX 5080‑class performance across the cloud gaming library, bringing higher frame rates, richer visuals and more responsive gameplay to even more of the games members already love. Ultimate members now get priority access to RTX 5080‑class rigs, making it easier than ever to tap into next‑generation PC power from almost any device. GeForce NOW is also celebrating 30 years of Firaxis in style, with more of the studio’s classics coming as Install‑to‑Play titles for instant access — just in time for a Steam celebration sale on select Firaxis games supported in the cloud. And this week kicks things off with six new games dropping into the cloud, setting the stage for a May packed with new adventures. AAA titles are landing throughout the month on their launch dates. Members can pick them up from their favorite PC stores — Steam, Xbox, PC Game Pass and GOG — and stream their PC gaming libraries instantly on GeForce NOW without having to repurchase titles to play across devices. The highly anticipated titles hitting the cloud this month include: Forza Horizon 6 from Playground Games: The Horizon festival is back and bigger than ever. This is Horizon Japan — stretching from the iconic downtown streets of Tokyo City all the way to the snowy Japanese Alps — introducing the most dense and vertical map yet. A massive new open world, a stacked car roster and that legendary “one more race” energy are all heading to GeForce NOW on the title’s launch date. Members can pick it up on PC via Steam and Xbox, including Game Pass, then hit full throttle from the cloud on almost any device. 007 First Light from IO Interactive: The game brings a modern James Bond origin story to the cloud when it launches Wednesday, May 27, for PC, inviting members to step into the shadows as Bond begins his journey. Experience a mix of stealth and action built around a “breathing” gameplay loop with IOI’s cinematic, set piece-driven storytelling. Approach encounters through stealth, direct action or creative improvisation, with multiple viable paths to each objective that let players define Bond’s style. It’s ready on day one for players grabbing it on Steam, Xbox on PC or GOG. GeForce NOW Ultimate is expanding what premium cloud gaming looks like. Starting today, Ultimate members can stream even more of their games on RTX 5080 virtual gaming rigs — bringing the power of the NVIDIA Blackwell RTX architecture to a wide range of titles. This update significantly broadens access to 5080 performance beyond the list of GeForce RTX 5080-optimized titles. Now, across nearly the entire GeForce NOW library, members can experience higher frame rates, richer visuals, and more responsive gameplay by default at up to 5K 120 frames per second or 360 fps at 1080p.",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260508-130818__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "skipped",
        "status_label": "暂不研判",
        "review_lane": "低信号",
        "review_score": 3,
        "review_reason": "这类内容更偏品牌、生态或营销更新，暂时看不到足够直接的业务、财务或估值影响。",
        "read_next": "保留存档；除非后续出现客户、金额、产品路线或财务影响，否则不升级。"
      },
      {
        "title": "Nemotron Labs: What OpenClaw Agents Mean for Every Organization",
        "date": "2026-04-30",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-04-30；标题：Nemotron Labs: What OpenClaw Agents Mean for Every Organization；原文内容：Editor’s note: This post is part of the Nemotron Labs blog series, which explores how the latest open models, datasets and training techniques help businesses build specialized AI systems and applications on NVIDIA platforms. Each post highlights practical ways to use an open stack to deliver real value in production — from transparent research copilots to scalable AI agents. By early 2026, the open source project O…；来源：https://blogs.nvidia.com/blog/what-openclaw-agents-mean-for-every-organization/",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260430,
        "source_url": "https://blogs.nvidia.com/blog/what-openclaw-agents-mean-for-every-organization/",
        "source_excerpt": "Editor’s note: This post is part of the Nemotron Labs blog series, which explores how the latest open models, datasets and training techniques help businesses build specialized AI systems and applications on NVIDIA platforms. Each post highlights practical ways to use an open stack to deliver real value in production — from transparent research copilots to scalable AI agents. By early 2026, the open source project O…",
        "source_body": "Editor’s note: This post is part of the Nemotron Labs blog series, which explores how the latest open models, datasets and training techniques help businesses build specialized AI systems and applications on NVIDIA platforms. Each post highlights practical ways to use an open stack to deliver real value in production — from transparent research copilots to scalable AI agents. By early 2026, the open source project OpenClaw had become a phenomenon. In January, its GitHub star count crossed 100,000 as developer interest surged. Community dashboards and traffic analytics showed more than 2 million visitors in a single week. By March, OpenClaw topped 250,000 stars — overtaking React to become the most-starred software project on GitHub in just 60 days. Created by Peter Steinberger , OpenClaw is a self-hosted, persistent AI assistant designed to run locally or on private servers. The project drew attention for its accessibility and unbounded autonomy: Users could deploy an AI model locally without depending on cloud infrastructure or external application programming interfaces (APIs). Most AI agents today are triggered by a prompt, complete a defined task and then stop running. A long-running autonomous agent, or “claw,” works differently. These agents run persistently in the background, completing tasks on their own and surfacing only what requires a human decision. They operate on a heartbeat: At regular intervals, they check their task list, evaluate what needs action, and either act or wait for the next cycle. To help enhance the security and robustness of the OpenClaw project, NVIDIA is collaborating with Steinberger and the OpenClaw developer community to address potential vulnerabilities, as detailed in a recent blog post by OpenClaw . NVIDIA contributes code and guidance focused on improving model isolation, better managing local data access and strengthening the processes for verifying community code contributions. The goal is to support the project’s momentum by contributing its security and systems expertise in an open, transparent way that strengthens the community’s work while preserving OpenClaw’s independent governance. To help make long-running agents safer for enterprises, NVIDIA also introduced NVIDIA NemoClaw, a reference implementation that uses a single command to install OpenClaw, the NVIDIA OpenShell secure runtime and NVIDIA Nemotron open models with hardened defaults for networking, data access and security. NemoClaw serves as a blueprint for organizations to deploy claws more securely. AI has moved through four phases, and the time between each is shortening. Predictive AI took years to become mainstream. Generative AI moved faster. Reasoning AI arrived faster still. Autonomous AI — the wave OpenClaw represents — is setting an even faster pace. What compounds with each wave is inference demand. Generative AI increased token usage over predictive AI. Reasoning AI increased it another 100x. Autonomous agents, which run continuously and act across long time horizons, drive inference demand up by another 1,000x over reasoning AI. Each wave multiplies the compute required. This increase in token usage is enabling organizations to speed their productivity by orders of magnitude. For example, long-running agents can help researchers work through a problem overnight, iterate on a design across thousands of configurations, or monitor systems and surface only the anomalies that require human judgment — freeing up researchers’ work days for higher-value tasks. While generative AI has become a staple for on-demand tasks, there are specific scenarios where the persistent “heartbeat” of a claw offers distinct advantages. Determining when to move from a standard prompt-based AI to a long-running agent often comes down to the nature of the workflow: The practical applications of long-running autonomous agents span every function and sector.",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260508-130818__investor.nvidia.com_news_press-releases_default.aspx.html",
        "company": "nvidia",
        "company_name": "NVIDIA",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 3,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      }
    ],
    "tsmc": [
      {
        "title": "Sony Semiconductor Solutions and TSMC Enter Preliminary Agreement for Next-Generation Image Sensor Strategic Partnership",
        "date": "2026-05-08",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-05-08；标题：Sony Semiconductor Solutions and TSMC Enter Preliminary Agreement for Next-Generation Image Sensor Strategic Partnership；来源：http://pr.tsmc.com/english/news/3308",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260508,
        "source_url": "http://pr.tsmc.com/english/news/3308",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260508-130818__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 5,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "先读交易/客户/合作的规模、期限、收入路径和利润影响；避免只凭标题判断。"
      },
      {
        "title": "TSMC April 2026 Revenue Report",
        "date": "2026-05-08",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-05-08；标题：TSMC April 2026 Revenue Report；来源：http://pr.tsmc.com/english/news/3305",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260508,
        "source_url": "http://pr.tsmc.com/english/news/3305",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260508-130818__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 7,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "TSMC Debuts A13 Technology at 2026 North America Technology Symposium",
        "date": "2026-04-23",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-04-23；标题：TSMC Debuts A13 Technology at 2026 North America Technology Symposium；来源：http://pr.tsmc.com/english/news/3302",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260423,
        "source_url": "http://pr.tsmc.com/english/news/3302",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260508-130818__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "promoted",
        "status_label": "已入库",
        "review_lane": "正式事件",
        "review_score": 14,
        "review_reason": "这条候选已经完成原文研判，并沉淀为正式事件；不再作为待读候选重复出现。",
        "read_next": "可直接进入对应公司主页或事件详情阅读正式研判。"
      },
      {
        "title": "TSMC Files Annual Report on Form 20-F for 2025",
        "date": "2026-04-16",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-04-16；标题：TSMC Files Annual Report on Form 20-F for 2025；来源：http://pr.tsmc.com/english/news/3300",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260416,
        "source_url": "http://pr.tsmc.com/english/news/3300",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260508-130818__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 7,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "适合周末深读：补风险、业务结构、资本开支和治理信息，先不要直接写成短期动作。"
      },
      {
        "title": "TSMC Reports First Quarter EPS of NT$22.08",
        "date": "2026-04-16",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-04-16；标题：TSMC Reports First Quarter EPS of NT$22.08；来源：http://pr.tsmc.com/english/news/3297",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260416,
        "source_url": "http://pr.tsmc.com/english/news/3297",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260508-130818__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 5,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "TSMC March 2026 Revenue Report",
        "date": "2026-04-10",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-04-10；标题：TSMC March 2026 Revenue Report；来源：http://pr.tsmc.com/english/news/3294",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260410,
        "source_url": "http://pr.tsmc.com/english/news/3294",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260508-130818__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 5,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "TSMC February 2026 Revenue Report",
        "date": "2026-03-10",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-03-10；标题：TSMC February 2026 Revenue Report；来源：http://pr.tsmc.com/english/news/3290",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260310,
        "source_url": "http://pr.tsmc.com/english/news/3290",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260508-130818__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 5,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "TSMC Board of Directors Meeting Resolutions",
        "date": "2026-02-10",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-02-10；标题：TSMC Board of Directors Meeting Resolutions；来源：http://pr.tsmc.com/english/news/3287",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260210,
        "source_url": "http://pr.tsmc.com/english/news/3287",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260508-130818__pr.tsmc.com_english_latest-news.html",
        "company": "tsmc",
        "company_name": "TSMC",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      }
    ],
    "inovance": [
      {
        "title": "2026春季爆品发布会",
        "date": "2026-03-16",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-03-16；标题：2026春季爆品发布会；来源：https://www.inovance.com/portal-front/api/product/launch/listPage?pageNum=1&pageSize=10",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260316,
        "source_url": "https://www.inovance.com/portal-front/api/product/launch/listPage?pageNum=1&pageSize=10",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260508-130818__www.inovance.com_portal-front_api_product_launch_listPage_pageNum_1_pageSize_10.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "2025年度爆品发布会",
        "date": "2025-09-01",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2025-09-01；标题：2025年度爆品发布会；来源：https://www.inovance.com/portal-front/api/product/launch/listPage?pageNum=1&pageSize=10",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250901,
        "source_url": "https://www.inovance.com/portal-front/api/product/launch/listPage?pageNum=1&pageSize=10",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260508-130818__www.inovance.com_portal-front_api_product_launch_listPage_pageNum_1_pageSize_10.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "邀请函｜ 「零碳有“数” ·智造有“方”」——2025汇川技术纺织行业新品发布会",
        "date": "2025-06-17",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2025-06-17；标题：邀请函｜ 「零碳有“数” ·智造有“方”」——2025汇川技术纺织行业新品发布会；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%96%B0%E5%93%81&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250617,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%96%B0%E5%93%81&showChannel=2",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260508-130818__www.inovance.com_portal-front_api_home_search_key_%E6%96%B0%E5%93%81_showChannel_2.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "数自融合，绿创未来！汇川技术应需而动，为纺织行业再推新品！",
        "date": "2022-11-21",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2022-11-21；标题：数自融合，绿创未来！汇川技术应需而动，为纺织行业再推新品！；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%96%B0%E5%93%81&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20221121,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%96%B0%E5%93%81&showChannel=2",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260508-130818__www.inovance.com_portal-front_api_home_search_key_%E6%96%B0%E5%93%81_showChannel_2.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "关于汇川技术机器人产品价格调整的通知",
        "date": "2026-03-30",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-03-30；标题：关于汇川技术机器人产品价格调整的通知；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260330,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260508-130818__www.inovance.com_portal-front_api_home_search_key_%E6%9C%BA%E5%99%A8%E4%BA%BA_showChannel_2.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "汇川技术机器人斩获德国TUV功能安全认证，全球化征程再添“安全引擎”",
        "date": "2025-05-09",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2025-05-09；标题：汇川技术机器人斩获德国TUV功能安全认证，全球化征程再添“安全引擎”；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250509,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260508-130818__www.inovance.com_portal-front_api_home_search_key_%E6%9C%BA%E5%99%A8%E4%BA%BA_showChannel_2.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "120000小时！汇川大六关节机器人MTBF认证达行业顶尖水平",
        "date": "2024-10-10",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2024-10-10；标题：120000小时！汇川大六关节机器人MTBF认证达行业顶尖水平；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20241010,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260508-130818__www.inovance.com_portal-front_api_home_search_key_%E6%9C%BA%E5%99%A8%E4%BA%BA_showChannel_2.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "120000小时！汇川大六关节机器人MTBF认证达行业顶尖水平",
        "date": "2024-10-08",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2024-10-08；标题：120000小时！汇川大六关节机器人MTBF认证达行业顶尖水平；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20241008,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260508-130818__www.inovance.com_portal-front_api_home_search_key_%E6%9C%BA%E5%99%A8%E4%BA%BA_showChannel_2.html",
        "company": "inovance",
        "company_name": "汇川技术",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      }
    ],
    "gevernova": [
      {
        "title": "4th Quarter 2025 Earnings Webcast",
        "date": "2026-01-28",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-01-28；标题：4th Quarter 2025 Earnings Webcast；来源：https://www.gevernova.com/investors/events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260128,
        "source_url": "https://www.gevernova.com/investors/events",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/gevernova__20260508-130818__www.gevernova.com_investors_events.html",
        "company": "gevernova",
        "company_name": "GE Vernova",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 6,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      }
    ],
    "luxshare": [
      {
        "title": "Luxshare Techday Debuts at Renault TCR: Showcasing Full-Chain Synergy for the Future of Mobility",
        "date": "2026-03-09",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-03-09；标题：Luxshare Techday Debuts at Renault TCR: Showcasing Full-Chain Synergy for the Future of Mobility；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260309,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260508-130818__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "​Gold Forges the Future: Luxshare Precision Once Again Wins Sina Finance's \"ESG Golden Responsibility Award\"",
        "date": "2026-01-19",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-01-19；标题：​Gold Forges the Future: Luxshare Precision Once Again Wins Sina Finance's \"ESG Golden Responsibility Award\"；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260119,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260508-130818__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "World's First! Luxshare Precision USB 40Gbps 240W USB Type-C 3m Active Cable Receives Official Certification",
        "date": "2026-01-05",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-01-05；标题：World's First! Luxshare Precision USB 40Gbps 240W USB Type-C 3m Active Cable Receives Official Certification；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260105,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260508-130818__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Luxshare Precision Named to Forbes' 2025 World's Best Employers List",
        "date": "2025-10-10",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2025-10-10；标题：Luxshare Precision Named to Forbes' 2025 World's Best Employers List；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20251010,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260508-130818__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Luxshare Precision Soars 65 Places on Fortune Global 500 Ranking!",
        "date": "2025-07-31",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2025-07-31；标题：Luxshare Precision Soars 65 Places on Fortune Global 500 Ranking!；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250731,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260508-130818__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Luxshare-ICT Tech Day at JLR UK: Shaping the Future of Intelligent Mobility with System-Level Innovations",
        "date": "2025-07-23",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2025-07-23；标题：Luxshare-ICT Tech Day at JLR UK: Shaping the Future of Intelligent Mobility with System-Level Innovations；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250723,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260508-130818__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "REACH and SVHC Statement",
        "date": "2025-07-22",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2025-07-22；标题：REACH and SVHC Statement；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250722,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260508-130818__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Luxshare Precision Celebrates Cross-Cultural Unity Through the “Luxshare Cup” Global Relay",
        "date": "2025-07-21",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2025-07-21；标题：Luxshare Precision Celebrates Cross-Cultural Unity Through the “Luxshare Cup” Global Relay；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250721,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260508-130818__www.luxshare-ict.com_en_news_release.html.html",
        "company": "luxshare",
        "company_name": "立讯精密",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      }
    ],
    "constellation": [
      {
        "title": "CERAWeek Highlights 2026",
        "date": "2026-03-27",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-03-27；标题：CERAWeek Highlights 2026；来源：https://www.constellationenergy.com/newsroom.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260327,
        "source_url": "https://www.constellationenergy.com/newsroom.html",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260508-130818__www.constellationenergy.com_newsroom.html.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Axios DC + AI Summit",
        "date": "2026-03-25",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-03-25；标题：Axios DC + AI Summit；来源：https://www.constellationenergy.com/newsroom.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260325,
        "source_url": "https://www.constellationenergy.com/newsroom.html",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260508-130818__www.constellationenergy.com_newsroom.html.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Constellation CEO: &#39;We Produce Enough Energy to Power Mexico&#39;",
        "date": "2026-01-20",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-01-20；标题：Constellation CEO: &#39;We Produce Enough Energy to Power Mexico&#39;；来源：https://www.constellationenergy.com/newsroom.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260120,
        "source_url": "https://www.constellationenergy.com/newsroom.html",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260508-130818__www.constellationenergy.com_newsroom.html.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "ENERGY: Always On",
        "date": "2025-11-18",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2025-11-18；标题：ENERGY: Always On；来源：https://www.constellationenergy.com/newsroom.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20251118,
        "source_url": "https://www.constellationenergy.com/newsroom.html",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260508-130818__www.constellationenergy.com_newsroom.html.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "archived",
        "status_label": "先存档",
        "review_lane": "低优先级",
        "review_score": 1,
        "review_reason": "当前信号不足以进入优先研判；先保存来源，避免把普通新闻包装成投资事件。",
        "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。"
      },
      {
        "title": "Q1 2026 Constellation Energy Corporation Earnings Conference Call",
        "date": "2026-05-11",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-05-11；标题：Q1 2026 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260511,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260508-130818__investors.constellationenergy.com_events-and-presentations.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 11,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "Constellation Energy Corporation 2026 Business and Earnings Outlook Conference Call",
        "date": "2026-03-31",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2026-03-31；标题：Constellation Energy Corporation 2026 Business and Earnings Outlook Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260331,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260508-130818__investors.constellationenergy.com_events-and-presentations_past-events.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "promoted",
        "status_label": "已入库",
        "review_lane": "正式事件",
        "review_score": 24,
        "review_reason": "这条候选已经完成原文研判，并沉淀为正式事件；不再作为待读候选重复出现。",
        "read_next": "可直接进入对应公司主页或事件详情阅读正式研判。"
      },
      {
        "title": "Q3 2025 Constellation Energy Corporation Earnings Conference Call",
        "date": "2025-11-07",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2025-11-07；标题：Q3 2025 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20251107,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260508-130818__investors.constellationenergy.com_events-and-presentations_past-events.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 9,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "Q2 2025 Constellation Energy Corporation Earnings Conference Call",
        "date": "2025-08-07",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2025-08-07；标题：Q2 2025 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250807,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260508-130818__investors.constellationenergy.com_events-and-presentations_past-events.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 9,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "Q1 2025 Constellation Energy Corporation Earnings Conference Call",
        "date": "2025-05-06",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2025-05-06；标题：Q1 2025 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250506,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260508-130818__investors.constellationenergy.com_events-and-presentations_past-events.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 9,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "Q3 2024 Constellation Energy Corporation Earnings Conference Call",
        "date": "2024-11-04",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2024-11-04；标题：Q3 2024 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20241104,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260508-130818__investors.constellationenergy.com_events-and-presentations_past-events.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 9,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      },
      {
        "title": "Q2 2024 Constellation Energy Corporation Earnings Conference Call",
        "date": "2024-08-06",
        "fetched_at": "20260508-130818",
        "type": "官方候选",
        "fact": "日期：2024-08-06；标题：Q2 2024 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20240806,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_excerpt": "",
        "source_body": "",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260508-130818__investors.constellationenergy.com_events-and-presentations_past-events.html",
        "company": "constellation",
        "company_name": "Constellation Energy",
        "candidate_status": "pending",
        "status_label": "待研判",
        "review_lane": "优先阅读",
        "review_score": 9,
        "review_reason": "标题中包含财报、展望、技术路线、客户合作或交易等投资相关信号，值得打开原文判断是否升级。",
        "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。"
      }
    ]
  }
};
