window.BAMBOO_LENS_CANDIDATES = {
  "generated_at": "2026-05-02T06:39:11",
  "companies": {
    "nvidia": [
      {
        "title": "From Rainforests to Recycling Plants: 5 Ways NVIDIA AI Is Protecting the Planet",
        "date": "2026-04-30",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-04-30；标题：From Rainforests to Recycling Plants: 5 Ways NVIDIA AI Is Protecting the Planet；来源：https://investor.nvidia.com/news/press-releases/default.aspx",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260430,
        "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-063733__investor.nvidia.com_news_press-releases_default.aspx.html"
      },
      {
        "title": "It’s Gonna Be May: 16 Games Hit the Cloud This Month, With More NVIDIA GeForce RTX 5080 Power",
        "date": "2026-04-30",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-04-30；标题：It’s Gonna Be May: 16 Games Hit the Cloud This Month, With More NVIDIA GeForce RTX 5080 Power；来源：https://investor.nvidia.com/news/press-releases/default.aspx",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260430,
        "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-063733__investor.nvidia.com_news_press-releases_default.aspx.html"
      },
      {
        "title": "OpenAI’s New GPT-5.5 Powers Codex on NVIDIA Infrastructure — and NVIDIA Is Already Putting It to Work",
        "date": "2026-04-23",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-04-23；标题：OpenAI’s New GPT-5.5 Powers Codex on NVIDIA Infrastructure — and NVIDIA Is Already Putting It to Work；来源：https://investor.nvidia.com/news/press-releases/default.aspx",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260423,
        "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-063733__investor.nvidia.com_news_press-releases_default.aspx.html"
      },
      {
        "title": "NVIDIA and Google Cloud Collaborate to Advance Agentic and Physical AI",
        "date": "2026-04-22",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-04-22；标题：NVIDIA and Google Cloud Collaborate to Advance Agentic and Physical AI；来源：https://investor.nvidia.com/news/press-releases/default.aspx",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260422,
        "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-063733__investor.nvidia.com_news_press-releases_default.aspx.html"
      },
      {
        "title": "NVIDIA's CEO Projects $1 Trillion in AI Chip Sales as New Computing Era Begins",
        "date": "2026-03-20",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-03-20；标题：NVIDIA's CEO Projects $1 Trillion in AI Chip Sales as New Computing Era Begins；来源：https://investor.nvidia.com/news/press-releases/default.aspx",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260320,
        "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-063733__investor.nvidia.com_news_press-releases_default.aspx.html"
      },
      {
        "title": "NVIDIA Beats Back Bubble Fears With Record $68 Billion in Sales in Fourth Quarter",
        "date": "2026-02-27",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-02-27；标题：NVIDIA Beats Back Bubble Fears With Record $68 Billion in Sales in Fourth Quarter；来源：https://investor.nvidia.com/news/press-releases/default.aspx",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260227,
        "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-063733__investor.nvidia.com_news_press-releases_default.aspx.html"
      },
      {
        "title": "NVIDIA Sets Conference Call for First-Quarter Financial Results",
        "date": "20260502-0",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：20260502-0；标题：NVIDIA Sets Conference Call for First-Quarter Financial Results；来源：https://investor.nvidia.com/news/press-releases/default.aspx",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260502,
        "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-063733__investor.nvidia.com_news_press-releases_default.aspx.html"
      },
      {
        "title": "NVIDIA Launches Nemotron 3 Nano Omni Model, Unifying Vision, Audio and Language for up to 9x More Efficient AI Agents",
        "date": "20260502-0",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：20260502-0；标题：NVIDIA Launches Nemotron 3 Nano Omni Model, Unifying Vision, Audio and Language for up to 9x More Efficient AI Agents；来源：https://investor.nvidia.com/news/press-releases/default.aspx",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260502,
        "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-063733__investor.nvidia.com_news_press-releases_default.aspx.html"
      }
    ],
    "tsmc": [
      {
        "title": "TSMC Debuts A13 Technology at 2026 North America Technology Symposium",
        "date": "2026-04-23",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-04-23；标题：TSMC Debuts A13 Technology at 2026 North America Technology Symposium；来源：https://pr.tsmc.com/english/latest-news",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260423,
        "source_url": "https://pr.tsmc.com/english/latest-news",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-063733__pr.tsmc.com_english_latest-news.html"
      },
      {
        "title": "TSMC Files Annual Report on Form 20-F for 2025",
        "date": "2026-04-16",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-04-16；标题：TSMC Files Annual Report on Form 20-F for 2025；来源：https://pr.tsmc.com/english/latest-news",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260416,
        "source_url": "https://pr.tsmc.com/english/latest-news",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-063733__pr.tsmc.com_english_latest-news.html"
      },
      {
        "title": "TSMC Reports First Quarter EPS of NT$22.08",
        "date": "2026-04-16",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-04-16；标题：TSMC Reports First Quarter EPS of NT$22.08；来源：https://pr.tsmc.com/english/latest-news",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260416,
        "source_url": "https://pr.tsmc.com/english/latest-news",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-063733__pr.tsmc.com_english_latest-news.html"
      },
      {
        "title": "TSMC March 2026 Revenue Report",
        "date": "2026-04-10",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-04-10；标题：TSMC March 2026 Revenue Report；来源：https://pr.tsmc.com/english/latest-news",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260410,
        "source_url": "https://pr.tsmc.com/english/latest-news",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-063733__pr.tsmc.com_english_latest-news.html"
      },
      {
        "title": "TSMC February 2026 Revenue Report",
        "date": "2026-03-10",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-03-10；标题：TSMC February 2026 Revenue Report；来源：https://pr.tsmc.com/english/latest-news",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260310,
        "source_url": "https://pr.tsmc.com/english/latest-news",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-063733__pr.tsmc.com_english_latest-news.html"
      },
      {
        "title": "TSMC Board of Directors Meeting Resolutions",
        "date": "2026-02-10",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-02-10；标题：TSMC Board of Directors Meeting Resolutions；来源：https://pr.tsmc.com/english/latest-news",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260210,
        "source_url": "https://pr.tsmc.com/english/latest-news",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-063733__pr.tsmc.com_english_latest-news.html"
      },
      {
        "title": "TSMC January 2026 Revenue Report",
        "date": "2026-02-10",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-02-10；标题：TSMC January 2026 Revenue Report；来源：https://pr.tsmc.com/english/latest-news",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260210,
        "source_url": "https://pr.tsmc.com/english/latest-news",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-063733__pr.tsmc.com_english_latest-news.html"
      },
      {
        "title": "TSMC Reports Fourth Quarter EPS of NT$19.50",
        "date": "2026-01-15",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-01-15；标题：TSMC Reports Fourth Quarter EPS of NT$19.50；来源：https://pr.tsmc.com/english/latest-news",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260115,
        "source_url": "https://pr.tsmc.com/english/latest-news",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-063733__pr.tsmc.com_english_latest-news.html"
      }
    ],
    "inovance": [
      {
        "title": "2026春季爆品发布会",
        "date": "2026-03-16",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-03-16；标题：2026春季爆品发布会；来源：https://www.inovance.com/portal-front/api/product/launch/listPage?pageNum=1&pageSize=10",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260316,
        "source_url": "https://www.inovance.com/portal-front/api/product/launch/listPage?pageNum=1&pageSize=10",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260502-063733__www.inovance.com_portal-front_api_product_launch_listPage_pageNum_1_pageSize_10.html"
      },
      {
        "title": "2025年度爆品发布会",
        "date": "2025-09-01",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-09-01；标题：2025年度爆品发布会；来源：https://www.inovance.com/portal-front/api/product/launch/listPage?pageNum=1&pageSize=10",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250901,
        "source_url": "https://www.inovance.com/portal-front/api/product/launch/listPage?pageNum=1&pageSize=10",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260502-063733__www.inovance.com_portal-front_api_product_launch_listPage_pageNum_1_pageSize_10.html"
      },
      {
        "title": "邀请函｜ 「零碳有“数” ·智造有“方”」——2025汇川技术纺织行业新品发布会",
        "date": "2025-06-17",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-06-17；标题：邀请函｜ 「零碳有“数” ·智造有“方”」——2025汇川技术纺织行业新品发布会；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%96%B0%E5%93%81&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250617,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%96%B0%E5%93%81&showChannel=2",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260502-063733__www.inovance.com_portal-front_api_home_search_key_%E6%96%B0%E5%93%81_showChannel_2.html"
      },
      {
        "title": "数自融合，绿创未来！汇川技术应需而动，为纺织行业再推新品！",
        "date": "2022-11-21",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2022-11-21；标题：数自融合，绿创未来！汇川技术应需而动，为纺织行业再推新品！；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%96%B0%E5%93%81&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20221121,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%96%B0%E5%93%81&showChannel=2",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260502-063733__www.inovance.com_portal-front_api_home_search_key_%E6%96%B0%E5%93%81_showChannel_2.html"
      },
      {
        "title": "关于汇川技术机器人产品价格调整的通知",
        "date": "2026-03-30",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-03-30；标题：关于汇川技术机器人产品价格调整的通知；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260330,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260502-063733__www.inovance.com_portal-front_api_home_search_key_%E6%9C%BA%E5%99%A8%E4%BA%BA_showChannel_2.html"
      },
      {
        "title": "汇川技术机器人斩获德国TUV功能安全认证，全球化征程再添“安全引擎”",
        "date": "2025-05-09",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-05-09；标题：汇川技术机器人斩获德国TUV功能安全认证，全球化征程再添“安全引擎”；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250509,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260502-063733__www.inovance.com_portal-front_api_home_search_key_%E6%9C%BA%E5%99%A8%E4%BA%BA_showChannel_2.html"
      },
      {
        "title": "120000小时！汇川大六关节机器人MTBF认证达行业顶尖水平",
        "date": "2024-10-10",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2024-10-10；标题：120000小时！汇川大六关节机器人MTBF认证达行业顶尖水平；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20241010,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260502-063733__www.inovance.com_portal-front_api_home_search_key_%E6%9C%BA%E5%99%A8%E4%BA%BA_showChannel_2.html"
      },
      {
        "title": "120000小时！汇川大六关节机器人MTBF认证达行业顶尖水平",
        "date": "2024-10-08",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2024-10-08；标题：120000小时！汇川大六关节机器人MTBF认证达行业顶尖水平；来源：https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20241008,
        "source_url": "https://www.inovance.com/portal-front/api/home/search?key=%E6%9C%BA%E5%99%A8%E4%BA%BA&showChannel=2",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/inovance__20260502-063733__www.inovance.com_portal-front_api_home_search_key_%E6%9C%BA%E5%99%A8%E4%BA%BA_showChannel_2.html"
      }
    ],
    "gevernova": [
      {
        "title": "4th Quarter 2025 Earnings Webcast",
        "date": "2026-01-28",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-01-28；标题：4th Quarter 2025 Earnings Webcast；来源：https://www.gevernova.com/investors/events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260128,
        "source_url": "https://www.gevernova.com/investors/events",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/gevernova__20260502-063733__www.gevernova.com_investors_events.html"
      }
    ],
    "luxshare": [
      {
        "title": "Luxshare Techday Debuts at Renault TCR: Showcasing Full-Chain Synergy for the Future of Mobility",
        "date": "2026-03-09",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-03-09；标题：Luxshare Techday Debuts at Renault TCR: Showcasing Full-Chain Synergy for the Future of Mobility；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260309,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260502-063733__www.luxshare-ict.com_en_news_release.html.html"
      },
      {
        "title": "​Gold Forges the Future: Luxshare Precision Once Again Wins Sina Finance's \"ESG Golden Responsibility Award\"",
        "date": "2026-01-19",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-01-19；标题：​Gold Forges the Future: Luxshare Precision Once Again Wins Sina Finance's \"ESG Golden Responsibility Award\"；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260119,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260502-063733__www.luxshare-ict.com_en_news_release.html.html"
      },
      {
        "title": "World's First! Luxshare Precision USB 40Gbps 240W USB Type-C 3m Active Cable Receives Official Certification",
        "date": "2026-01-05",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-01-05；标题：World's First! Luxshare Precision USB 40Gbps 240W USB Type-C 3m Active Cable Receives Official Certification；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260105,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260502-063733__www.luxshare-ict.com_en_news_release.html.html"
      },
      {
        "title": "Luxshare Precision Named to Forbes' 2025 World's Best Employers List",
        "date": "2025-10-10",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-10-10；标题：Luxshare Precision Named to Forbes' 2025 World's Best Employers List；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20251010,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260502-063733__www.luxshare-ict.com_en_news_release.html.html"
      },
      {
        "title": "Luxshare Precision Soars 65 Places on Fortune Global 500 Ranking!",
        "date": "2025-07-31",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-07-31；标题：Luxshare Precision Soars 65 Places on Fortune Global 500 Ranking!；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250731,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260502-063733__www.luxshare-ict.com_en_news_release.html.html"
      },
      {
        "title": "Luxshare-ICT Tech Day at JLR UK: Shaping the Future of Intelligent Mobility with System-Level Innovations",
        "date": "2025-07-23",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-07-23；标题：Luxshare-ICT Tech Day at JLR UK: Shaping the Future of Intelligent Mobility with System-Level Innovations；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250723,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260502-063733__www.luxshare-ict.com_en_news_release.html.html"
      },
      {
        "title": "REACH and SVHC Statement",
        "date": "2025-07-22",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-07-22；标题：REACH and SVHC Statement；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250722,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260502-063733__www.luxshare-ict.com_en_news_release.html.html"
      },
      {
        "title": "Luxshare Precision Celebrates Cross-Cultural Unity Through the “Luxshare Cup” Global Relay",
        "date": "2025-07-21",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-07-21；标题：Luxshare Precision Celebrates Cross-Cultural Unity Through the “Luxshare Cup” Global Relay；来源：https://www.luxshare-ict.com/en/news/release.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250721,
        "source_url": "https://www.luxshare-ict.com/en/news/release.html",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/luxshare__20260502-063733__www.luxshare-ict.com_en_news_release.html.html"
      }
    ],
    "constellation": [
      {
        "title": "Constellation CEO: &#39;We Produce Enough Energy to Power Mexico&#39;",
        "date": "2026-01-20",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-01-20；标题：Constellation CEO: &#39;We Produce Enough Energy to Power Mexico&#39;；来源：https://www.constellationenergy.com/newsroom.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260120,
        "source_url": "https://www.constellationenergy.com/newsroom.html",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-063733__www.constellationenergy.com_newsroom.html.html"
      },
      {
        "title": "ENERGY: Always On",
        "date": "2025-11-18",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-11-18；标题：ENERGY: Always On；来源：https://www.constellationenergy.com/newsroom.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20251118,
        "source_url": "https://www.constellationenergy.com/newsroom.html",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-063733__www.constellationenergy.com_newsroom.html.html"
      },
      {
        "title": "Aspen Ideas Festival 2025",
        "date": "2025-07-21",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-07-21；标题：Aspen Ideas Festival 2025；来源：https://www.constellationenergy.com/newsroom.html",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250721,
        "source_url": "https://www.constellationenergy.com/newsroom.html",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-063733__www.constellationenergy.com_newsroom.html.html"
      },
      {
        "title": "Q1 2026 Constellation Energy Corporation Earnings Conference Call",
        "date": "2026-05-11",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-05-11；标题：Q1 2026 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260511,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-063733__investors.constellationenergy.com_events-and-presentations.html"
      },
      {
        "title": "Constellation Energy Corporation 2026 Business and Earnings Outlook Conference Call",
        "date": "2026-03-31",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2026-03-31；标题：Constellation Energy Corporation 2026 Business and Earnings Outlook Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20260331,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-063733__investors.constellationenergy.com_events-and-presentations_past-events.html"
      },
      {
        "title": "Q3 2025 Constellation Energy Corporation Earnings Conference Call",
        "date": "2025-11-07",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-11-07；标题：Q3 2025 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20251107,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-063733__investors.constellationenergy.com_events-and-presentations_past-events.html"
      },
      {
        "title": "Q2 2025 Constellation Energy Corporation Earnings Conference Call",
        "date": "2025-08-07",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-08-07；标题：Q2 2025 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250807,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-063733__investors.constellationenergy.com_events-and-presentations_past-events.html"
      },
      {
        "title": "Q1 2025 Constellation Energy Corporation Earnings Conference Call",
        "date": "2025-05-06",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2025-05-06；标题：Q1 2025 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20250506,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-063733__investors.constellationenergy.com_events-and-presentations_past-events.html"
      },
      {
        "title": "Q3 2024 Constellation Energy Corporation Earnings Conference Call",
        "date": "2024-11-04",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2024-11-04；标题：Q3 2024 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20241104,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-063733__investors.constellationenergy.com_events-and-presentations_past-events.html"
      },
      {
        "title": "Q2 2024 Constellation Energy Corporation Earnings Conference Call",
        "date": "2024-08-06",
        "fetched_at": "20260502-063733",
        "type": "官方候选",
        "fact": "日期：2024-08-06；标题：Q2 2024 Constellation Energy Corporation Earnings Conference Call；来源：https://investors.constellationenergy.com/events-and-presentations/past-events",
        "judgment": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
        "action": "加入待研判队列",
        "priority": "候选",
        "sort_key": 20240806,
        "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
        "source_file": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-063733__investors.constellationenergy.com_events-and-presentations_past-events.html"
      }
    ]
  }
};
