window.BAMBOO_LENS_DECISION_QUEUE = {
  "generated_at": "2026-05-02T05:18:23",
  "source_generated_at": "2026-05-02T05:18:23",
  "items": [
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "TSMC Reports First Quarter EPS of NT$22.08",
      "date": "2026-04-16",
      "type": "财报",
      "priority": "P1",
      "decision_action": "提升优先级",
      "why": "这是 TSMC 最关键的季度经营更新之一，通常会直接影响市场对先进制程需求、盈利能力和资本开支回报的判断。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-051627__pr.tsmc.com_english_latest-news.html",
      "event_index": 2,
      "sort_key": 20260416,
      "score": 26
    },
    {
      "company": "constellation",
      "company_name": "Constellation Energy",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2026 年 3 月 31 日业务与业绩展望会议，正式把公司重心拉向“长期成长型电力平台”",
      "date": "2026-03-31",
      "type": "管理层展望 / 投资者沟通",
      "priority": "P2",
      "decision_action": "仅记录，不调整评级",
      "why": "这条信息本身不是硬业绩，但很重要。它说明管理层已经明确把公司定位从传统公用事业，升级为面向未来大负荷需求的清洁与可靠电力平台。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/27-Constellation Energy动态更新样例V1.md",
      "event_index": 4,
      "sort_key": 20260331,
      "score": 25
    },
    {
      "company": "alibaba",
      "company_name": "阿里巴巴",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2025 年 12 月季度，云业务增速明显加快，AI 继续成为增长引擎",
      "date": "2026-03-19",
      "type": "财报",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这是一条 P1 级别的强化信息。它说明阿里的云和 AI 不是边缘业务，而是在持续成长为新的长期价值中枢。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/20-阿里巴巴动态更新样例V1.md",
      "event_index": 0,
      "sort_key": 20260319,
      "score": 23
    },
    {
      "company": "constellation",
      "company_name": "Constellation Energy",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2025 全年业绩继续超指引中枢，股东回报进一步上调",
      "date": "2026-02-24",
      "type": "财报",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这是 P1 级别的强化信息。它说明 Constellation 的底层经营质量和股东回报能力并没有被大规模并购和成长叙事稀释，反而在继续加强。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/27-Constellation Energy动态更新样例V1.md",
      "event_index": 0,
      "sort_key": 20260224,
      "score": 23
    },
    {
      "company": "microsoft",
      "company_name": "Microsoft",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "FY26 Q2 收入和利润继续高质量增长，Microsoft Cloud 单季收入突破 500 亿美元",
      "date": "2026-01-28",
      "type": "财报",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这是 P1 级别的强化信息。它说明微软的 AI 和云逻辑并不是单点业务驱动，而是在继续扩展整个云和企业平台的收入基础。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/24-Microsoft动态更新样例V1.md",
      "event_index": 0,
      "sort_key": 20260128,
      "score": 21
    },
    {
      "company": "microsoft",
      "company_name": "Microsoft",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "Intelligent Cloud 继续高速增长，Azure 所在业务板块成为最关键的经营抓手",
      "date": "2026-01-28",
      "type": "财报",
      "priority": "P1",
      "decision_action": "提升优先级",
      "why": "这进一步强化了微软“平台型现金流资产 + AI 增长引擎”的复合逻辑。微软未来价值中枢是否继续上移，核心还是看云和 AI 能不能协同放大。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/24-Microsoft动态更新样例V1.md",
      "event_index": 1,
      "sort_key": 20260128,
      "score": 21
    },
    {
      "company": "gevernova",
      "company_name": "GE Vernova",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2026 年 4 月 22 日一季度业绩会，是下一次最关键验证点",
      "date": "2026-04-22",
      "type": "预告 / 下一次验证点",
      "priority": "P1",
      "decision_action": "等待验证",
      "why": "这是当前最重要的近端验证点。我们需要重点看三件事：1）订单与 backlog 是否继续高增长；2）Power 和 Electrification 利润率是否继续改善；3）并购并表后 Electrification 的增长质量是否增强。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/26-GE Vernova动态更新样例V1.md",
      "event_index": 4,
      "sort_key": 20260422,
      "score": 20
    },
    {
      "company": "nvidia",
      "company_name": "NVIDIA",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "FY26 Q4 与全年业绩再创新高，数据中心业务继续主导增长",
      "date": "2026-02-25",
      "type": "财报",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这是 P1 级别的强化信息。它说明 NVIDIA 仍然处在 AI 基础设施主线最中心的位置，而且增长并没有因为高基数而明显失速。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/28-NVIDIA动态更新样例V1.md",
      "event_index": 0,
      "sort_key": 20260225,
      "score": 19
    },
    {
      "company": "gevernova",
      "company_name": "GE Vernova",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2025 年第四季度订单和 backlog 明显跳升，Power 与 Electrification 同时强化",
      "date": "2026-01-28",
      "type": "财报",
      "priority": "P1",
      "decision_action": "提升优先级",
      "why": "这是 P1 级别的强化信息。它说明电力系统投资并不是分散小修小补，而是在核心设备和服务层面形成了更长、更强的需求可见性。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/26-GE Vernova动态更新样例V1.md",
      "event_index": 0,
      "sort_key": 20260128,
      "score": 19
    },
    {
      "company": "gevernova",
      "company_name": "GE Vernova",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2025 全年收入、利润率和自由现金流继续改善，经营质量明显提升",
      "date": "2026-01-28",
      "type": "财报",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这条信息非常重要，因为它表明 GE Vernova 的长期逻辑已经不只是“订单多”，而是订单正在更系统地转化为利润率与现金流改善。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/26-GE Vernova动态更新样例V1.md",
      "event_index": 1,
      "sort_key": 20260128,
      "score": 18
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2025 年第四季度收入、利润和利润率继续走强，先进制程占比进一步抬升",
      "date": "2026-01-15",
      "type": "财报",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这是 P1 级别的强化信息。它说明 TSMC 的增长不是来自成熟制程反弹，而是高价值先进制程继续主导收入结构。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/25-TSMC动态更新样例V1.md",
      "event_index": 9,
      "sort_key": 20260115,
      "score": 18
    },
    {
      "company": "constellation",
      "company_name": "Constellation Energy",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "Constellation Energy Corporation 2026 Business and Earnings Outlook Conference Call",
      "date": "2026-03-31",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-051627__investors.constellationenergy.com_events-and-presentations_past-events.html",
      "event_index": null,
      "sort_key": 20260331,
      "score": 17
    },
    {
      "company": "nvidia",
      "company_name": "NVIDIA",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "FY27 Q1 指引继续上修到 780 亿美元，但公司明确不假设来自中国的数据中心计算收入",
      "date": "2026-02-25",
      "type": "财报指引",
      "priority": "P1",
      "decision_action": "提升优先级",
      "why": "这条信息非常关键，因为它说明即使在相对保守的地缘假设下，公司仍然给出非常强的增长与盈利能力指引。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/28-NVIDIA动态更新样例V1.md",
      "event_index": 1,
      "sort_key": 20260225,
      "score": 17
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "管理层对 2026 年第一季度给出高位指引，领先制程需求仍然强劲",
      "date": "2026-01-15",
      "type": "财报指引",
      "priority": "P1",
      "decision_action": "提升优先级",
      "why": "这条信息很关键，因为它说明市场最关心的“AI 需求会不会很快降温”暂时没有在公司官方口径里出现，相反，TSMC 仍在按高强度需求来安排产能和资本开支。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/25-TSMC动态更新样例V1.md",
      "event_index": 10,
      "sort_key": 20260115,
      "score": 17
    },
    {
      "company": "inovance",
      "company_name": "汇川技术",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "公司继续强调多产品组合销售和平台化扩张",
      "date": "2025-08-26",
      "type": "财报 / 业务结构",
      "priority": "P1",
      "decision_action": "提升优先级",
      "why": "这强化了“平台型工业公司”而非“单品公司”的长期逻辑。对汇川这种公司来说，真正值得给高跟踪优先级的原因，就在于它可能从几个强产品演进成完整解决方案平台。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/23-汇川技术动态更新样例V1.md",
      "event_index": 2,
      "sort_key": 20250826,
      "score": 17
    },
    {
      "company": "microsoft",
      "company_name": "Microsoft",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "Azure 和企业 AI 的增长已经从“概念验证”进入“兑现验证”",
      "date": "2025-10-29 至 2026-01-28",
      "type": "财报 / 管理层表述",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这说明微软已经跨过“AI 会不会贡献收入”的早期阶段，进入“AI 收入和投入能否持续形成高质量经营杠杆”的阶段。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/24-Microsoft动态更新样例V1.md",
      "event_index": 2,
      "sort_key": 20260128,
      "score": 16
    },
    {
      "company": "microsoft",
      "company_name": "Microsoft",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "OpenAI 投资波动提醒我们，微软的 AI 逻辑不能只看收入，还要看收益质量",
      "date": "2025-10-29 至 2026-01-28",
      "type": "财报 / 非 GAAP 说明",
      "priority": "P2",
      "decision_action": "需要二次验证",
      "why": "这是一条 P2 级别的提醒信息。长期逻辑没被削弱，但它提醒我们，微软的 AI 叙事需要和投资收益波动、资本开支与真实经营质量分开看。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/24-Microsoft动态更新样例V1.md",
      "event_index": 3,
      "sort_key": 20260128,
      "score": 16
    },
    {
      "company": "microsoft",
      "company_name": "Microsoft",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "资本开支和云基础设施投入仍然是估值能否持续的关键变量",
      "date": "2025-07-30 至 2026-01-28",
      "type": "资本配置 / 财报",
      "priority": "P2",
      "decision_action": "维持原判断",
      "why": "这说明微软后续最关键的验证点已经不是“会不会投”，而是“投入是否持续带来足够高质量的商业回报”。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/24-Microsoft动态更新样例V1.md",
      "event_index": 4,
      "sort_key": 20260128,
      "score": 16
    },
    {
      "company": "luxshare",
      "company_name": "立讯精密",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2025 年一季度收入和利润继续增长，但经营现金流明显承压",
      "date": "2025-04-26",
      "type": "财报",
      "priority": "P1",
      "decision_action": "需要二次验证",
      "why": "这是一条“偏正面但带警示”的信息。它说明立讯的经营扩张仍在继续，但现金流压力明显加大，尤其对 A 股制造龙头来说，这是必须持续观察的质量信号。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/18-立讯精密动态更新样例V1.md",
      "event_index": 0,
      "sort_key": 20250426,
      "score": 16
    },
    {
      "company": "constellation",
      "company_name": "Constellation Energy",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "Q1 2026 Constellation Energy Corporation Earnings Conference Call",
      "date": "2026-05-11",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://investors.constellationenergy.com/events-and-presentations",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-051627__investors.constellationenergy.com_events-and-presentations.html",
      "event_index": null,
      "sort_key": 20260511,
      "score": 14
    },
    {
      "company": "nvidia",
      "company_name": "NVIDIA",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "NVIDIA Sets Conference Call for First-Quarter Financial Results",
      "date": "20260502-0",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-051627__investor.nvidia.com_news_press-releases_default.aspx.html",
      "event_index": null,
      "sort_key": 20260502,
      "score": 14
    },
    {
      "company": "alibaba",
      "company_name": "阿里巴巴",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "阿里正在强化“全栈 AI”叙事，从模型、芯片、云到应用形成一体化",
      "date": "2025-09-29 至 2026-03-19",
      "type": "产品/技术",
      "priority": "P1",
      "decision_action": "提升优先级",
      "why": "这是阿里最值得长期跟踪的变化之一。若这套一体化能力持续兑现，它就不再只是“估值受压的平台公司”，而更像“中国 AI 基础设施与应用平台的复合体”。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/20-阿里巴巴动态更新样例V1.md",
      "event_index": 2,
      "sort_key": 20260319,
      "score": 14
    },
    {
      "company": "nvidia",
      "company_name": "NVIDIA",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "高增长继续，但毛利率、库存与客户集中度仍然需要持续验证",
      "date": "2025-11-19 / 2026-02-25",
      "type": "财报 / 风险跟踪",
      "priority": "P2",
      "decision_action": "需要二次验证",
      "why": "这是一条 P2 级别的提醒信息。长期逻辑没有被削弱，但后续必须把毛利率、库存变化和超大客户 capex 波动一起看，而不能只看收入。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/28-NVIDIA动态更新样例V1.md",
      "event_index": 4,
      "sort_key": 20260225,
      "score": 14
    },
    {
      "company": "nvidia",
      "company_name": "NVIDIA",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "Meta 扩大与 NVIDIA 的多代际合作，进一步验证超大客户资本开支强度",
      "date": "2026-02-17",
      "type": "客户 / 合作",
      "priority": "P1",
      "decision_action": "提升优先级",
      "why": "这是 P1 级别的信息。它强化了一个关键结论：NVIDIA 的增长不只是短期订单高景气，而是被头部平台客户写进了多年资本开支路线图。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/28-NVIDIA动态更新样例V1.md",
      "event_index": 2,
      "sort_key": 20260217,
      "score": 14
    },
    {
      "company": "inovance",
      "company_name": "汇川技术",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2025 年前三季度收入和利润继续双位数增长，主航道经营延续强势",
      "date": "2025-10-24",
      "type": "财报",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这是 P1 级别的强化信息。它说明汇川不只是短期订单反弹，而是平台型工业公司在多个业务线上同步释放增长。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/23-汇川技术动态更新样例V1.md",
      "event_index": 0,
      "sort_key": 20251024,
      "score": 14
    },
    {
      "company": "inovance",
      "company_name": "汇川技术",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2025 年上半年，通用自动化和新能源汽车业务双轮驱动更清晰",
      "date": "2025-08-26",
      "type": "财报",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这条信息非常重要，因为它说明公司并不是只靠单一行业吃景气，而是“工业自动化 + 电驱系统”双轮驱动在继续强化。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/23-汇川技术动态更新样例V1.md",
      "event_index": 1,
      "sort_key": 20250826,
      "score": 14
    },
    {
      "company": "luxshare",
      "company_name": "立讯精密",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2024 年全年收入和利润保持双位数增长，业务边界继续扩展",
      "date": "2025-04-26",
      "type": "财报",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这强化了“立讯不是单一消费电子链公司”的长期逻辑。它已经在往更广义的复杂制造平台演进。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/18-立讯精密动态更新样例V1.md",
      "event_index": 1,
      "sort_key": 20250426,
      "score": 14
    },
    {
      "company": "gevernova",
      "company_name": "GE Vernova",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "管理层继续强化“electricity supercycle”叙事，但当前更该跟踪兑现质量",
      "date": "2026-01-28 / 2026-03-18",
      "type": "管理层表述 / 投资者沟通",
      "priority": "P2",
      "decision_action": "仅记录，不调整评级",
      "why": "这条信息本身不新鲜，但很重要。因为它提醒我们：GE Vernova 的研究已经不能停留在“赛道正确”层面，而要转向“赛道红利是否稳定兑现为 backlog 质量、利润率和现金流”。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/26-GE Vernova动态更新样例V1.md",
      "event_index": 3,
      "sort_key": 20260318,
      "score": 12
    },
    {
      "company": "constellation",
      "company_name": "Constellation Energy",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "与 CyrusOne 的数据中心供电协议，验证了大负荷客户长期供电能力",
      "date": "2026-02-09",
      "type": "客户 / 合同 / 数据中心",
      "priority": "P1",
      "decision_action": "提升优先级",
      "why": "这是 P1 级别的信息。它让“数据中心长期供电”从概念走向实单，也强化了 Constellation 在 AI 用电周期中的战略位置。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/27-Constellation Energy动态更新样例V1.md",
      "event_index": 2,
      "sort_key": 20260209,
      "score": 12
    },
    {
      "company": "gevernova",
      "company_name": "GE Vernova",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "Prolec GE 并购完成，进一步强化北美电网设备供给能力",
      "date": "2026-02-02",
      "type": "并购 / 业务扩张",
      "priority": "P1",
      "decision_action": "提升优先级",
      "why": "这是一条 P1 级别的强化信息。它让 GE Vernova 在北美电网设备与变压器链条上的位置更强，也让 Electrification 这条主线更清晰。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/26-GE Vernova动态更新样例V1.md",
      "event_index": 2,
      "sort_key": 20260202,
      "score": 12
    },
    {
      "company": "constellation",
      "company_name": "Constellation Energy",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "Calpine 并购于 2026 年 1 月完成，Constellation 成为美国最大私营发电平台",
      "date": "2026-01-07",
      "type": "并购 / 业务扩张",
      "priority": "P1",
      "decision_action": "提升优先级",
      "why": "这是一条 P1 级别的强化信息。它明显改变了公司边界，使其从“核电稀缺资产持有者”升级为更完整的电力与能源解决方案平台。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/27-Constellation Energy动态更新样例V1.md",
      "event_index": 1,
      "sort_key": 20260107,
      "score": 12
    },
    {
      "company": "constellation",
      "company_name": "Constellation Energy",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "Q3 2025 Constellation Energy Corporation Earnings Conference Call",
      "date": "2025-11-07",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-051627__investors.constellationenergy.com_events-and-presentations_past-events.html",
      "event_index": null,
      "sort_key": 20251107,
      "score": 12
    },
    {
      "company": "constellation",
      "company_name": "Constellation Energy",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "Q2 2025 Constellation Energy Corporation Earnings Conference Call",
      "date": "2025-08-07",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-051627__investors.constellationenergy.com_events-and-presentations_past-events.html",
      "event_index": null,
      "sort_key": 20250807,
      "score": 12
    },
    {
      "company": "constellation",
      "company_name": "Constellation Energy",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "Q1 2025 Constellation Energy Corporation Earnings Conference Call",
      "date": "2025-05-06",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-051627__investors.constellationenergy.com_events-and-presentations_past-events.html",
      "event_index": null,
      "sort_key": 20250506,
      "score": 12
    },
    {
      "company": "constellation",
      "company_name": "Constellation Energy",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "Q3 2024 Constellation Energy Corporation Earnings Conference Call",
      "date": "2024-11-04",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-051627__investors.constellationenergy.com_events-and-presentations_past-events.html",
      "event_index": null,
      "sort_key": 20241104,
      "score": 12
    },
    {
      "company": "constellation",
      "company_name": "Constellation Energy",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "Q2 2024 Constellation Energy Corporation Earnings Conference Call",
      "date": "2024-08-06",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://investors.constellationenergy.com/events-and-presentations/past-events",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/constellation__20260502-051627__investors.constellationenergy.com_events-and-presentations_past-events.html",
      "event_index": null,
      "sort_key": 20240806,
      "score": 12
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "TSMC Files Annual Report on Form 20-F for 2025",
      "date": "2026-04-16",
      "type": "年报",
      "priority": "P3",
      "decision_action": "维持原判断",
      "why": "年报文件更适合沉淀长期研究底稿，短期交易价值次于季度业绩和月度营收，但对补全风险、治理和资本配置细节很重要。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-051627__pr.tsmc.com_english_latest-news.html",
      "event_index": 1,
      "sort_key": 20260416,
      "score": 11
    },
    {
      "company": "nvidia",
      "company_name": "NVIDIA",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "Rubin 平台、NVLink Fusion 和光互连合作，说明公司正在继续向更完整的 AI 工厂平台扩张",
      "date": "2026-01-05 / 2026-03-02 / 2026-03-16 / 2026-03-31",
      "type": "产品 / 平台 / 供应链",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这是一条 P1 级别的信息。它说明 NVIDIA 正在从“最强 AI 芯片公司”继续演进为“AI 工厂平台公司”，未来护城河越来越依赖系统级协同，而不是单点芯片领先。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/28-NVIDIA动态更新样例V1.md",
      "event_index": 3,
      "sort_key": 20260331,
      "score": 11
    },
    {
      "company": "constellation",
      "company_name": "Constellation Energy",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "为满足监管要求出售部分 PJM 资产，提醒我们要把并购整合与监管成本一起看",
      "date": "2026-03-18",
      "type": "监管 / 资产处置",
      "priority": "P2",
      "decision_action": "需要二次验证",
      "why": "这是一条 P2 级别的信息。它没有破坏长期逻辑，但提醒我们：Calpine 并购的价值不能只看规模扩张，还要把监管约束、资产剥离和整合难度一起纳入跟踪。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/27-Constellation Energy动态更新样例V1.md",
      "event_index": 3,
      "sort_key": 20260318,
      "score": 11
    },
    {
      "company": "nvidia",
      "company_name": "NVIDIA",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "It’s Gonna Be May: 16 Games Hit the Cloud This Month, With More NVIDIA GeForce RTX 5080 Power",
      "date": "2026-04-30",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。",
      "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-051627__investor.nvidia.com_news_press-releases_default.aspx.html",
      "event_index": null,
      "sort_key": 20260430,
      "score": 10
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2026 年 4 月 16 日的一季度法说会，成为下一次最关键验证点",
      "date": "2026-04-16",
      "type": "预告 / 下一次验证点",
      "priority": "P1",
      "decision_action": "等待验证",
      "why": "这本身不是业绩强化信息，但它是当前最重要的近端验证点。到 2026 年 4 月 16 日，我们需要重点看三个问题：1）2nm 和先进封装需求是否继续偏紧；2）海外扩产是否继续影响利润率；3）资本开支与回报的平衡是否仍可接受。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/25-TSMC动态更新样例V1.md",
      "event_index": 0,
      "sort_key": 20260416,
      "score": 10
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "TSMC March 2026 Revenue Report",
      "date": "2026-04-10",
      "type": "月度营收",
      "priority": "P2",
      "decision_action": "继续跟踪",
      "why": "月度营收报告能帮助我们更快验证 AI、HPC 与先进制程需求是否仍在延续，是季度财报之间最有价值的高频跟踪点之一。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-051627__pr.tsmc.com_english_latest-news.html",
      "event_index": 3,
      "sort_key": 20260410,
      "score": 9
    },
    {
      "company": "alibaba",
      "company_name": "阿里巴巴",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "Qwen App 用户增长和开源模型生态强化了消费侧与开发者侧双轮驱动",
      "date": "2026-03-19",
      "type": "产品/技术",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这意味着阿里的 AI 逻辑不只是企业端云服务，还在往消费端入口和开发者生态延展。对平台公司而言，这是很重要的结构性信号。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/20-阿里巴巴动态更新样例V1.md",
      "event_index": 1,
      "sort_key": 20260319,
      "score": 9
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "2026 年 1 月和 2 月营收继续保持较高同比增长，年初需求验证仍然稳健",
      "date": "2026-02-10 / 2026-03-10",
      "type": "月度营收",
      "priority": "P1",
      "decision_action": "保持核心跟踪",
      "why": "这是 P1 级别的验证信息。它说明进入 2026 年之后，高基数之下需求并没有明显失速，AI / HPC 相关强度仍在支撑台积电的收入表现。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/25-TSMC动态更新样例V1.md",
      "event_index": 4,
      "sort_key": 20260310,
      "score": 9
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "TSMC February 2026 Revenue Report",
      "date": "2026-03-10",
      "type": "月度营收",
      "priority": "P2",
      "decision_action": "继续跟踪",
      "why": "月度营收报告能帮助我们更快验证 AI、HPC 与先进制程需求是否仍在延续，是季度财报之间最有价值的高频跟踪点之一。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-051627__pr.tsmc.com_english_latest-news.html",
      "event_index": 5,
      "sort_key": 20260310,
      "score": 9
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "董事会继续大额批准资本支出与相关融资安排，扩产节奏没有放缓",
      "date": "2026-02-10",
      "type": "董事会 / 资本配置",
      "priority": "P2",
      "decision_action": "需要二次验证",
      "why": "这是一条 P2 级别的信息。正面之处在于，管理层对长期需求和技术路线仍然非常坚定；需要持续跟踪的是，全球扩产与海外建厂会不会阶段性稀释资本回报和利润结构。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/25-TSMC动态更新样例V1.md",
      "event_index": 6,
      "sort_key": 20260210,
      "score": 9
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "TSMC January 2026 Revenue Report",
      "date": "2026-02-10",
      "type": "月度营收",
      "priority": "P2",
      "decision_action": "继续跟踪",
      "why": "月度营收报告能帮助我们更快验证 AI、HPC 与先进制程需求是否仍在延续，是季度财报之间最有价值的高频跟踪点之一。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-051627__pr.tsmc.com_english_latest-news.html",
      "event_index": 8,
      "sort_key": 20260210,
      "score": 9
    },
    {
      "company": "gevernova",
      "company_name": "GE Vernova",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "4th Quarter 2025 Earnings Webcast",
      "date": "2026-01-28",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://www.gevernova.com/investors/events",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/gevernova__20260502-051627__www.gevernova.com_investors_events.html",
      "event_index": null,
      "sort_key": 20260128,
      "score": 9
    },
    {
      "company": "alibaba",
      "company_name": "阿里巴巴",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "可转债融资说明公司愿意继续为云和国际业务扩张筹集长期资本",
      "date": "2025-09-11",
      "type": "资本配置",
      "priority": "P2",
      "decision_action": "需要二次验证",
      "why": "这是偏中性的信号。它不是坏事，因为用途与战略主航道一致；但也意味着阿里在新阶段愿意用更长期资本支持扩张，未来要继续观察投入回报效率。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/20-阿里巴巴动态更新样例V1.md",
      "event_index": 4,
      "sort_key": 20250911,
      "score": 9
    },
    {
      "company": "nvidia",
      "company_name": "NVIDIA",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "NVIDIA Launches Nemotron 3 Nano Omni Model, Unifying Vision, Audio and Language for up to 9x More Efficient AI Agents",
      "date": "20260502-0",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。",
      "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-051627__investor.nvidia.com_news_press-releases_default.aspx.html",
      "event_index": null,
      "sort_key": 20260502,
      "score": 8
    },
    {
      "company": "nvidia",
      "company_name": "NVIDIA",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "From Rainforests to Recycling Plants: 5 Ways NVIDIA AI Is Protecting the Planet",
      "date": "2026-04-30",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。",
      "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-051627__investor.nvidia.com_news_press-releases_default.aspx.html",
      "event_index": null,
      "sort_key": 20260430,
      "score": 8
    },
    {
      "company": "nvidia",
      "company_name": "NVIDIA",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "OpenAI’s New GPT-5.5 Powers Codex on NVIDIA Infrastructure — and NVIDIA Is Already Putting It to Work",
      "date": "2026-04-23",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。",
      "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-051627__investor.nvidia.com_news_press-releases_default.aspx.html",
      "event_index": null,
      "sort_key": 20260423,
      "score": 8
    },
    {
      "company": "nvidia",
      "company_name": "NVIDIA",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "NVIDIA and Google Cloud Collaborate to Advance Agentic and Physical AI",
      "date": "2026-04-22",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "先读交易/客户/合作的规模、期限、收入路径和利润影响；避免只凭标题判断。",
      "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-051627__investor.nvidia.com_news_press-releases_default.aspx.html",
      "event_index": null,
      "sort_key": 20260422,
      "score": 8
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "TSMC Files Annual Report on Form 20-F for 2025",
      "date": "2026-04-16",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "适合周末深读：补风险、业务结构、资本开支和治理信息，先不要直接写成短期动作。",
      "source_url": "https://pr.tsmc.com/english/latest-news",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-051627__pr.tsmc.com_english_latest-news.html",
      "event_index": null,
      "sort_key": 20260416,
      "score": 8
    },
    {
      "company": "luxshare",
      "company_name": "立讯精密",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "公司在 2026 年启动较大规模回购",
      "date": "2026-01-16 至 2026-02-24",
      "type": "资本配置",
      "priority": "P2",
      "decision_action": "维持原判断",
      "why": "这说明管理层愿意在当前阶段动用真金白银回购，至少释放出对公司长期价值和员工绑定的信号。但因为回购主要用于激励，不等同于纯粹的股东回报，正面但不过度高估。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/18-立讯精密动态更新样例V1.md",
      "event_index": 3,
      "sort_key": 20260224,
      "score": 7
    },
    {
      "company": "inovance",
      "company_name": "汇川技术",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "出海能力正在从叙事变成订单验证",
      "date": "2025-08-26 至 2026-01-07",
      "type": "出海 / 产品 / 展会",
      "priority": "P2",
      "decision_action": "维持原判断",
      "why": "这是一条 P2 级别的正向信息。它说明汇川出海不再只是渠道铺设，而是在产品和解决方案层面开始建立国际存在感。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/23-汇川技术动态更新样例V1.md",
      "event_index": 3,
      "sort_key": 20260107,
      "score": 7
    },
    {
      "company": "alibaba",
      "company_name": "阿里巴巴",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "持续回购说明管理层仍在通过资本配置支持股东回报",
      "date": "2025-04-02、2025-07-02、2025-10-02",
      "type": "资本配置",
      "priority": "P2",
      "decision_action": "维持原判断",
      "why": "对港股/中概平台资产而言，回购并不是边缘信息，而是估值框架的一部分。阿里持续回购有助于证明管理层愿意把现金流转化为股东回报。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/20-阿里巴巴动态更新样例V1.md",
      "event_index": 3,
      "sort_key": 20251002,
      "score": 7
    },
    {
      "company": "luxshare",
      "company_name": "立讯精密",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "汽车业务继续向系统级方案延展",
      "date": "2025-07-23",
      "type": "产品/技术",
      "priority": "P2",
      "decision_action": "维持原判断",
      "why": "这说明汽车业务不再只是零部件切入，而是在往更高价值、更系统级的环节上走。对长期逻辑是加分项。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/长期高潜力公司跟踪系统/18-立讯精密动态更新样例V1.md",
      "event_index": 2,
      "sort_key": 20250723,
      "score": 7
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "TSMC Reports First Quarter EPS of NT$22.08",
      "date": "2026-04-16",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://pr.tsmc.com/english/latest-news",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-051627__pr.tsmc.com_english_latest-news.html",
      "event_index": null,
      "sort_key": 20260416,
      "score": 6
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "TSMC March 2026 Revenue Report",
      "date": "2026-04-10",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://pr.tsmc.com/english/latest-news",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-051627__pr.tsmc.com_english_latest-news.html",
      "event_index": null,
      "sort_key": 20260410,
      "score": 6
    },
    {
      "company": "nvidia",
      "company_name": "NVIDIA",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "NVIDIA's CEO Projects $1 Trillion in AI Chip Sales as New Computing Era Begins",
      "date": "2026-03-20",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "先打开官方来源阅读全文，提取事实和数字；如果只有标题或营销话术，就保留候选不升级。",
      "source_url": "https://investor.nvidia.com/news/press-releases/default.aspx",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/nvidia__20260502-051627__investor.nvidia.com_news_press-releases_default.aspx.html",
      "event_index": null,
      "sort_key": 20260320,
      "score": 6
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "TSMC February 2026 Revenue Report",
      "date": "2026-03-10",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://pr.tsmc.com/english/latest-news",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-051627__pr.tsmc.com_english_latest-news.html",
      "event_index": null,
      "sort_key": 20260310,
      "score": 6
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "TSMC January 2026 Revenue Report",
      "date": "2026-02-10",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://pr.tsmc.com/english/latest-news",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-051627__pr.tsmc.com_english_latest-news.html",
      "event_index": null,
      "sort_key": 20260210,
      "score": 6
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "official_candidate",
      "stage": "待读原文",
      "title": "TSMC Reports Fourth Quarter EPS of NT$19.50",
      "date": "2026-01-15",
      "type": "官方候选",
      "priority": "候选",
      "decision_action": "进入研判队列",
      "why": "这是云端从官方页面自动抓到的候选更新，需进一步研判后再升级为正式研究事件。",
      "read_next": "优先读原文里的收入、利润率、指引、现金流和管理层口径；够具体后再升级为正式事件。",
      "source_url": "https://pr.tsmc.com/english/latest-news",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-051627__pr.tsmc.com_english_latest-news.html",
      "event_index": null,
      "sort_key": 20260115,
      "score": 6
    },
    {
      "company": "tsmc",
      "company_name": "TSMC",
      "source_type": "formal_event",
      "stage": "已入库事件",
      "title": "TSMC Board of Directors Meeting Resolutions",
      "date": "2026-02-10",
      "type": "资本配置",
      "priority": "P2",
      "decision_action": "继续跟踪",
      "why": "董事会决议往往涉及资本开支、股东回报或重要治理动作，对评估资本配置质量很有参考意义。",
      "read_next": "打开事件详情，核对事实、判断、估值/动作影响，并决定是否回写公司主页当前结论。",
      "source_url": "",
      "source_doc": "/home/runner/work/bamboo-lens/bamboo-lens/云端研究简报系统/outputs/snapshots/tsmc__20260502-051627__pr.tsmc.com_english_latest-news.html",
      "event_index": 7,
      "sort_key": 20260210,
      "score": 5
    }
  ],
  "summary": {
    "total": 65,
    "formal_events": 44,
    "official_candidates": 21,
    "companies": 8
  }
};
